import ConvexFilters.Defs

/-!
# Convex filters: basic lattice facts and the maximality criterion

This file contains elementary facts about half-spaces and hyperplanes, and the
maximality criterion (Lemma 2.1): a convex filter is maximal precisely when every
closed convex set not belonging to it is disjoint from some member of it.
-/

namespace ConvexFilter

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V] {F : ConvexFilter V}

/-! ### Basic lattice facts -/

theorem nonempty_of_mem {C : Set V} (hC : C ∈ F.carrier) : C.Nonempty := by
  rcases Set.eq_empty_or_nonempty C with rfl | h
  · exact absurd hC F.empty_not_mem
  · exact h

theorem isClosed_halfLE (u : V →L[ℝ] ℝ) (t : ℝ) : IsClosed (halfLE u t) :=
  isClosed_le u.continuous continuous_const

theorem convex_halfLE (u : V →L[ℝ] ℝ) (t : ℝ) : Convex ℝ (halfLE u t) :=
  convex_halfSpace_le (LinearMap.isLinear u.toLinearMap) t

theorem isClosed_halfGE (u : V →L[ℝ] ℝ) (t : ℝ) : IsClosed (halfGE u t) :=
  isClosed_le continuous_const u.continuous

theorem convex_halfGE (u : V →L[ℝ] ℝ) (t : ℝ) : Convex ℝ (halfGE u t) :=
  convex_halfSpace_ge (LinearMap.isLinear u.toLinearMap) t

theorem isClosed_hyperplane (u : V →L[ℝ] ℝ) (t : ℝ) : IsClosed (hyperplane u t) :=
  isClosed_eq u.continuous continuous_const

/-- Hyperplanes are convex. -/
theorem convex_hyperplane (u : V →L[ℝ] ℝ) (t : ℝ) : Convex ℝ (hyperplane u t) :=
  _root_.convex_hyperplane (LinearMap.isLinear u.toLinearMap) t

theorem halfLE_neg (u : V →L[ℝ] ℝ) (t : ℝ) : halfLE (-u) (-t) = halfGE u t := by
  ext x
  simp only [halfLE, halfGE, Set.mem_setOf_eq, ContinuousLinearMap.neg_apply, neg_le_neg_iff]

theorem halfGE_neg (u : V →L[ℝ] ℝ) (t : ℝ) : halfGE (-u) (-t) = halfLE u t := by
  ext x
  simp only [halfLE, halfGE, Set.mem_setOf_eq, ContinuousLinearMap.neg_apply, neg_le_neg_iff]

theorem hyperplane_neg (u : V →L[ℝ] ℝ) (t : ℝ) : hyperplane (-u) (-t) = hyperplane u t := by
  ext x
  simp only [hyperplane, Set.mem_setOf_eq, ContinuousLinearMap.neg_apply, neg_inj]

theorem halfLE_inter_halfGE (u : V →L[ℝ] ℝ) (t : ℝ) :
    halfLE u t ∩ halfGE u t = hyperplane u t := by
  ext x
  simp only [halfLE, halfGE, hyperplane, Set.mem_inter_iff, Set.mem_setOf_eq]
  constructor
  · rintro ⟨h₁, h₂⟩; exact le_antisymm h₁ h₂
  · rintro h; exact ⟨h.le, h.ge⟩

theorem halfLE_smul {c : ℝ} (hc : 0 < c) (u : V →L[ℝ] ℝ) (t : ℝ) :
    halfLE (c • u) (c * t) = halfLE u t := by
  ext x
  simp only [halfLE, Set.mem_setOf_eq, ContinuousLinearMap.smul_apply, smul_eq_mul,
    mul_le_mul_iff_of_pos_left hc]

theorem halfLE_inter_subset_add (u v : V →L[ℝ] ℝ) (s t : ℝ) :
    halfLE u s ∩ halfLE v t ⊆ halfLE (u + v) (s + t) := by
  rintro x ⟨hx, hy⟩
  simpa [halfLE] using add_le_add hx hy

theorem disjoint_halfLE_halfGE {t s : ℝ} (h : t < s) (u : V →L[ℝ] ℝ) :
    halfLE u t ∩ halfGE u s = ∅ := by
  ext x
  simp only [halfLE, halfGE, Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_empty_iff_false,
    iff_false, not_and, not_le]
  intro hx
  exact lt_of_le_of_lt hx h

/-! ### The maximality criterion (Lemma 2.1) -/

/-- The convex filter generated by a convex filter `F` together with a closed convex set `C`
meeting every member of `F`. -/
def adjoin (F : ConvexFilter V) (C : Set V)
    (hmeet : ∀ D ∈ F.carrier, (C ∩ D).Nonempty) : ConvexFilter V where
  carrier := {X : Set V | IsClosed X ∧ Convex ℝ X ∧ ∃ D ∈ F.carrier, C ∩ D ⊆ X}
  isClosed_of_mem := fun _ hX => hX.1
  convex_of_mem := fun _ hX => hX.2.1
  univ_mem := ⟨isClosed_univ, convex_univ, Set.univ, F.univ_mem, Set.subset_univ _⟩
  empty_not_mem := by
    rintro ⟨-, -, D, hD, hsub⟩
    exact (hmeet D hD).ne_empty (Set.subset_empty_iff.mp hsub)
  inter_mem := by
    rintro X Y ⟨hXcl, hXcv, D₁, hD₁, hs₁⟩ ⟨hYcl, hYcv, D₂, hD₂, hs₂⟩
    refine ⟨hXcl.inter hYcl, hXcv.inter hYcv, D₁ ∩ D₂, F.inter_mem hD₁ hD₂, ?_⟩
    rintro x ⟨hxC, hxD₁, hxD₂⟩
    exact ⟨hs₁ ⟨hxC, hxD₁⟩, hs₂ ⟨hxC, hxD₂⟩⟩
  mem_of_superset := by
    rintro X Y ⟨-, -, D, hD, hs⟩ hYcl hYcv hXY
    exact ⟨hYcl, hYcv, D, hD, hs.trans hXY⟩

theorem subset_adjoin (F : ConvexFilter V) (C : Set V)
    (hmeet : ∀ D ∈ F.carrier, (C ∩ D).Nonempty) :
    F.carrier ⊆ (adjoin F C hmeet).carrier := by
  intro D hD
  exact ⟨F.isClosed_of_mem hD, F.convex_of_mem hD, D, hD, Set.inter_subset_right⟩

theorem mem_adjoin (F : ConvexFilter V) {C : Set V} (hCcl : IsClosed C) (hCcv : Convex ℝ C)
    (hmeet : ∀ D ∈ F.carrier, (C ∩ D).Nonempty) :
    C ∈ (adjoin F C hmeet).carrier :=
  ⟨hCcl, hCcv, Set.univ, F.univ_mem, Set.inter_subset_left⟩

theorem isMaximal_iff (F : ConvexFilter V) :
    IsMaximal F ↔
      ∀ ⦃C : Set V⦄, IsClosed C → Convex ℝ C → C ∉ F.carrier →
        ∃ D ∈ F.carrier, C ∩ D = ∅ := by
  constructor
  · intro hF C hCcl hCcv hCF
    by_contra hcon
    push_neg at hcon
    have hmeet : ∀ D ∈ F.carrier, (C ∩ D).Nonempty := by
      intro D hD
      exact hcon D hD
    exact hCF (hF _ (subset_adjoin F C hmeet) (mem_adjoin F hCcl hCcv hmeet))
  · intro h G hFG C hC
    by_contra hCF
    obtain ⟨D, hD, hCD⟩ := h (G.isClosed_of_mem hC) (G.convex_of_mem hC) hCF
    have : (∅ : Set V) ∈ G.carrier := by
      rw [← hCD]
      exact G.inter_mem hC (hFG hD)
    exact G.empty_not_mem this

end ConvexFilter
