import ConvexFilters.Basic

/-!
# Convex filters: bases and maximal extensions

This file provides the two tools needed to exhibit concrete maximal convex filters:

* `ofAntitoneBase` — the convex filter generated by an antitone sequence of nonempty
  closed convex sets;
* `exists_isMaximal_extension` — every convex filter is contained in a maximal one
  (Zorn's lemma; the union of a chain of convex filters is a convex filter).

Neither is used by the contract theorems of the campaign; they support the counterexample
of `ConvexFilters/SigCounterexample.lean`.
-/

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

namespace ConvexFilter

/-- The convex filter generated by an antitone sequence of nonempty closed convex sets:
its members are the closed convex sets containing some member of the sequence. -/
def ofAntitoneBase (B : ℕ → Set V) (hne : ∀ n, (B n).Nonempty) (hanti : Antitone B) :
    ConvexFilter V where
  carrier := {C : Set V | IsClosed C ∧ Convex ℝ C ∧ ∃ n, B n ⊆ C}
  isClosed_of_mem := fun _ h => h.1
  convex_of_mem := fun _ h => h.2.1
  univ_mem := ⟨isClosed_univ, convex_univ, 0, Set.subset_univ _⟩
  empty_not_mem := by
    rintro ⟨-, -, n, hn⟩
    obtain ⟨x, hx⟩ := hne n
    exact hn hx
  inter_mem := by
    rintro C D ⟨hCcl, hCcv, n, hn⟩ ⟨hDcl, hDcv, m, hm⟩
    refine ⟨hCcl.inter hDcl, hCcv.inter hDcv, max n m, ?_⟩
    intro x hx
    exact ⟨hn (hanti (le_max_left n m) hx), hm (hanti (le_max_right n m) hx)⟩
  mem_of_superset := by
    rintro C D ⟨-, -, n, hn⟩ hDcl hDcv hCD
    exact ⟨hDcl, hDcv, n, hn.trans hCD⟩

theorem base_mem_ofAntitoneBase {B : ℕ → Set V} {hne : ∀ n, (B n).Nonempty}
    {hanti : Antitone B} {n : ℕ} (hcl : IsClosed (B n)) (hcv : Convex ℝ (B n)) :
    B n ∈ (ofAntitoneBase B hne hanti).carrier :=
  ⟨hcl, hcv, n, subset_rfl⟩

/-- The union of a chain of convex filters, as a convex filter. -/
private def sUnionOfChain (c : Set (Set (Set V)))
    (hc : ∀ s ∈ c, ∃ G : ConvexFilter V, G.carrier = s) (hchain : IsChain (· ⊆ ·) c)
    (hne : c.Nonempty) : ConvexFilter V where
  carrier := ⋃₀ c
  isClosed_of_mem := by
    rintro C ⟨s, hs, hCs⟩
    obtain ⟨G, rfl⟩ := hc s hs
    exact G.isClosed_of_mem hCs
  convex_of_mem := by
    rintro C ⟨s, hs, hCs⟩
    obtain ⟨G, rfl⟩ := hc s hs
    exact G.convex_of_mem hCs
  univ_mem := by
    obtain ⟨s, hs⟩ := hne
    obtain ⟨G, rfl⟩ := hc s hs
    exact ⟨G.carrier, hs, G.univ_mem⟩
  empty_not_mem := by
    rintro ⟨s, hs, hCs⟩
    obtain ⟨G, rfl⟩ := hc s hs
    exact G.empty_not_mem hCs
  inter_mem := by
    rintro C D ⟨s, hs, hCs⟩ ⟨s', hs', hDs'⟩
    rcases eq_or_ne s s' with rfl | hne'
    · obtain ⟨G, rfl⟩ := hc s hs
      exact ⟨G.carrier, hs, G.inter_mem hCs hDs'⟩
    · rcases hchain hs hs' hne' with h | h
      · obtain ⟨G, rfl⟩ := hc s' hs'
        exact ⟨G.carrier, hs', G.inter_mem (h hCs) hDs'⟩
      · obtain ⟨G, rfl⟩ := hc s hs
        exact ⟨G.carrier, hs, G.inter_mem hCs (h hDs')⟩
  mem_of_superset := by
    rintro C D ⟨s, hs, hCs⟩ hDcl hDcv hCD
    obtain ⟨G, rfl⟩ := hc s hs
    exact ⟨G.carrier, hs, G.mem_of_superset hCs hDcl hDcv hCD⟩

/-- Every convex filter is contained in a maximal convex filter. -/
theorem exists_isMaximal_extension (F : ConvexFilter V) :
    ∃ G : ConvexFilter V, F.carrier ⊆ G.carrier ∧ IsMaximal G := by
  classical
  set S : Set (Set (Set V)) :=
    {s : Set (Set V) | (∃ G : ConvexFilter V, G.carrier = s) ∧ F.carrier ⊆ s} with hS
  have hchainub : ∀ c ⊆ S, IsChain (· ⊆ ·) c → c.Nonempty → ∃ ub ∈ S, ∀ s ∈ c, s ⊆ ub := by
    intro c hcS hchain hcne
    have hc : ∀ s ∈ c, ∃ G : ConvexFilter V, G.carrier = s := fun s hs => (hcS hs).1
    refine ⟨⋃₀ c, ⟨⟨sUnionOfChain c hc hchain hcne, rfl⟩, ?_⟩, fun s hs => Set.subset_sUnion_of_mem hs⟩
    obtain ⟨s, hs⟩ := hcne
    exact (hcS hs).2.trans (Set.subset_sUnion_of_mem hs)
  have hFS : F.carrier ∈ S := ⟨⟨F, rfl⟩, subset_rfl⟩
  obtain ⟨m, hFm, hmax⟩ := zorn_subset_nonempty S hchainub F.carrier hFS
  obtain ⟨⟨G, hG⟩, -⟩ := hmax.prop
  refine ⟨G, hG ▸ hFm, ?_⟩
  intro H hGH
  have hHS : H.carrier ∈ S := ⟨⟨H, rfl⟩, (hG ▸ hFm : F.carrier ⊆ G.carrier).trans hGH⟩
  have : H.carrier ⊆ m := hmax.le_of_ge hHS (hG ▸ hGH)
  rw [hG]
  exact this

end ConvexFilter
