import ConvexFilters.Fibres

/-!
# Functions with limits along maximal convex filters: the generated filter and the algebra

WO-13, Parts A and B; Section 2 of `paper/limits-algebra-note.tex`.

A convex filter `F` is a filter of the lattice of closed convex sets; it generates an
honest filter `toFilter F` of subsets of `V`, and since `F.carrier` contains `Set.univ`
and is stable under binary intersections, the generated filter has no members beyond the
supersets of members of `F` (`mem_toFilter_iff`).  It is proper (`neBot`) because `∅` is
not a member of a convex filter.

`HasLim f F` says that `f : V → ℝ` converges along `toFilter F`, `lim f F` is the value of
the limit, and `mem_A f` is the note's `f ∈ 𝒜`: convergence along *every* maximal convex
filter.

## Contents

* Part A: `toFilter`, `mem_toFilter_iff`, `neBot`, `HasLim`, `lim`, `tendsto_lim`, `mem_A`;
* Part B: Propositions 2.2 and 2.3 of the note — `mem_A` is a subalgebra
  (`mem_A_const`, `mem_A_add`, `mem_A_mul`, `mem_A_smul`), each `lim · F` is an algebra
  homomorphism (`lim_add`, `lim_mul`, `lim_const`), the limit along a principal filter is
  evaluation (`lim_principal`), and a non-principal maximal filter has a member missing
  any prescribed bounded set (`exists_mem_disjoint_of_not_principal`).
-/

open Filter Topology

namespace ConvexFilter

namespace Limits

/-! ## Part A — the generated filter -/

section PartA

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- The filter of subsets of `V` generated by a convex filter. -/
def toFilter (F : ConvexFilter V) : Filter V := Filter.generate F.carrier

/-- A finite intersection of members of a convex filter is a member. -/
theorem sInter_mem_carrier {F : ConvexFilter V} {t : Set (Set V)} (ht : t.Finite)
    (hts : t ⊆ F.carrier) : ⋂₀ t ∈ F.carrier := by
  induction t, ht using Set.Finite.induction_on with
  | empty => simpa using F.univ_mem
  | @insert C s _hCs _hs ih =>
      have hC : C ∈ F.carrier := hts (Set.mem_insert _ _)
      have hsub : s ⊆ F.carrier := fun D hD => hts (Set.mem_insert_of_mem _ hD)
      rw [Set.sInter_insert]
      exact F.inter_mem hC (ih hsub)

/-- The generated filter has no members beyond the supersets of members of `F`. -/
theorem mem_toFilter_iff {F : ConvexFilter V} {S : Set V} :
    S ∈ toFilter F ↔ ∃ C ∈ F.carrier, C ⊆ S := by
  constructor
  · intro hS
    obtain ⟨t, hts, htfin, htS⟩ := Filter.mem_generate_iff.mp hS
    exact ⟨⋂₀ t, sInter_mem_carrier htfin hts, htS⟩
  · rintro ⟨C, hC, hCS⟩
    exact Filter.mem_of_superset (Filter.mem_generate_of_mem hC) hCS

/-- A member of a convex filter is a member of the generated filter. -/
theorem mem_toFilter_of_mem_carrier {F : ConvexFilter V} {C : Set V} (hC : C ∈ F.carrier) :
    C ∈ toFilter F := mem_toFilter_iff.mpr ⟨C, hC, subset_rfl⟩

/-- The generated filter is proper: a convex filter does not contain `∅`. -/
instance neBot (F : ConvexFilter V) : (toFilter F).NeBot := by
  refine ⟨fun hbot => ?_⟩
  have hmem : (∅ : Set V) ∈ toFilter F := Filter.empty_mem_iff_bot.mpr hbot
  obtain ⟨C, hC, hCe⟩ := mem_toFilter_iff.mp hmem
  exact F.empty_not_mem (Set.subset_empty_iff.mp hCe ▸ hC)

/-- `f` converges along the filter generated by `F`. -/
def HasLim (f : V → ℝ) (F : ConvexFilter V) : Prop :=
  ∃ L : ℝ, Filter.Tendsto f (toFilter F) (nhds L)

open Classical in
/-- The limit of `f` along `F`, when it exists; `0` otherwise. -/
noncomputable def lim (f : V → ℝ) (F : ConvexFilter V) : ℝ :=
  if h : HasLim f F then h.choose else 0

theorem tendsto_lim {f : V → ℝ} {F : ConvexFilter V} (h : HasLim f F) :
    Filter.Tendsto f (toFilter F) (nhds (lim f F)) := by
  classical
  rw [lim, dif_pos h]
  exact h.choose_spec

/-- The limit along a convex filter is unique. -/
theorem lim_eq_of_tendsto {f : V → ℝ} {F : ConvexFilter V} {L : ℝ}
    (h : Filter.Tendsto f (toFilter F) (nhds L)) : lim f F = L :=
  tendsto_nhds_unique (tendsto_lim ⟨L, h⟩) h

theorem hasLim_of_tendsto {f : V → ℝ} {F : ConvexFilter V} {L : ℝ}
    (h : Filter.Tendsto f (toFilter F) (nhds L)) : HasLim f F := ⟨L, h⟩

/-- The note's algebra `𝒜`: the functions converging along every maximal convex filter. -/
def mem_A (f : V → ℝ) : Prop := ∀ F : ConvexFilter V, IsMaximal F → HasLim f F

end PartA

/-! ## Part B — the algebra and the two reductions -/

section PartB

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

theorem mem_A_const (c : ℝ) : mem_A (fun _ : V => c) :=
  fun _ _ => ⟨c, tendsto_const_nhds⟩

theorem mem_A_add {f g : V → ℝ} (hf : mem_A f) (hg : mem_A g) : mem_A (f + g) := by
  intro F hF
  obtain ⟨L, hL⟩ := hf F hF
  obtain ⟨M, hM⟩ := hg F hF
  exact ⟨L + M, hL.add hM⟩

theorem mem_A_mul {f g : V → ℝ} (hf : mem_A f) (hg : mem_A g) : mem_A (f * g) := by
  intro F hF
  obtain ⟨L, hL⟩ := hf F hF
  obtain ⟨M, hM⟩ := hg F hF
  exact ⟨L * M, hL.mul hM⟩

theorem mem_A_smul {c : ℝ} {f : V → ℝ} (hf : mem_A f) : mem_A (c • f) := by
  intro F hF
  obtain ⟨L, hL⟩ := hf F hF
  exact ⟨c * L, by simpa [Pi.smul_apply, smul_eq_mul] using hL.const_mul c⟩

/-- The limit of a sum is the sum of the limits.  The maximality hypothesis is not needed
for the proof; it is kept as the contract specifies it (see `notes/CONVENTIONS.md`, §6). -/
theorem lim_add {f g : V → ℝ} {F : ConvexFilter V} (hF : IsMaximal F) (hf : HasLim f F)
    (hg : HasLim g F) : lim (f + g) F = lim f F + lim g F :=
  lim_eq_of_tendsto ((tendsto_lim hf).add (tendsto_lim hg))

/-- The limit of a product is the product of the limits.  The maximality hypothesis is not
needed for the proof; it is kept as the contract specifies it. -/
theorem lim_mul {f g : V → ℝ} {F : ConvexFilter V} (hF : IsMaximal F) (hf : HasLim f F)
    (hg : HasLim g F) : lim (f * g) F = lim f F * lim g F :=
  lim_eq_of_tendsto ((tendsto_lim hf).mul (tendsto_lim hg))

theorem lim_const (F : ConvexFilter V) (c : ℝ) : lim (fun _ : V => c) F = c :=
  lim_eq_of_tendsto tendsto_const_nhds

theorem lim_smul {c : ℝ} {f : V → ℝ} {F : ConvexFilter V} (hf : HasLim f F) :
    lim (c • f) F = c * lim f F :=
  lim_eq_of_tendsto (by simpa [Pi.smul_apply, smul_eq_mul] using (tendsto_lim hf).const_mul c)

end PartB

/-! ### The two reductions of Proposition 2.3 -/

section Reductions

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V] [FiniteDimensional ℝ V]

omit [FiniteDimensional ℝ V] in
/-- The filter generated by the principal convex filter at `p` is the principal filter of
`p` in the ordinary sense. -/
theorem toFilter_principal (p : V) : toFilter (principal p) = pure p := by
  ext S
  rw [mem_toFilter_iff, Filter.mem_pure]
  constructor
  · rintro ⟨C, ⟨-, -, hpC⟩, hCS⟩
    exact hCS hpC
  · intro hp
    exact ⟨{p}, ⟨isClosed_singleton, convex_singleton p, rfl⟩, Set.singleton_subset_iff.mpr hp⟩

omit [FiniteDimensional ℝ V] in
theorem hasLim_principal (f : V → ℝ) (p : V) : HasLim f (principal p) :=
  ⟨f p, by rw [toFilter_principal]; exact tendsto_pure_nhds f p⟩

omit [FiniteDimensional ℝ V] in
/-- The limit along a principal filter is evaluation. -/
theorem lim_principal (f : V → ℝ) (p : V) : lim f (principal p) = f p :=
  lim_eq_of_tendsto (by rw [toFilter_principal]; exact tendsto_pure_nhds f p)

/-- A non-principal maximal convex filter has a functional whose support value is `+∞`. -/
theorem exists_lev_eq_empty_of_not_principal {F : ConvexFilter V} (hF : IsMaximal F)
    (hnp : ∀ p, F.carrier ≠ (principal p).carrier) : ∃ u : V →L[ℝ] ℝ, lev F u = ∅ := by
  have hN : Nset F ≠ Set.univ := by
    intro h
    obtain ⟨p, hp⟩ := eq_principal_of_Nset_univ hF h
    exact hnp p hp
  obtain ⟨u, hu⟩ : ∃ u : V →L[ℝ] ℝ, u ∉ Nset F := by
    by_contra hcon
    push_neg at hcon
    exact hN (Set.eq_univ_of_forall hcon)
  rw [Nset, Set.mem_setOf_eq, not_and_or, not_ne_iff, not_ne_iff] at hu
  rcases hu with h | h
  · exact ⟨u, h⟩
  · exact ⟨-u, h⟩

/-- **Proposition 2.3 of the note.** A non-principal maximal convex filter has a member
disjoint from any prescribed bounded set. -/
theorem exists_mem_disjoint_of_not_principal {F : ConvexFilter V} (hF : IsMaximal F)
    (hnp : ∀ p, F.carrier ≠ (principal p).carrier) (B : Set V) (hB : Bornology.IsBounded B) :
    ∃ C ∈ F.carrier, C ∩ B = ∅ := by
  obtain ⟨u, hu⟩ := exists_lev_eq_empty_of_not_principal hF hnp
  obtain ⟨r, hr⟩ := hB.subset_closedBall (0 : V)
  set t : ℝ := ‖u‖ * r + 1 with ht
  have hmem : halfGE u t ∈ F.carrier := by
    refine halfGE_of_not_halfLE hF ?_
    intro hcon
    have : t ∈ lev F u := hcon
    rw [hu] at this
    exact this
  refine ⟨halfGE u t, hmem, ?_⟩
  ext x
  simp only [Set.mem_inter_iff, Set.mem_empty_iff_false, iff_false, not_and]
  intro hx hxB
  have hnorm : ‖x‖ ≤ r := by
    have := hr hxB
    simpa [Metric.mem_closedBall] using this
  have h1 : u x ≤ ‖u‖ * ‖x‖ := le_trans (le_abs_self _) (u.le_opNorm x)
  have h2 : ‖u‖ * ‖x‖ ≤ ‖u‖ * r := by
    exact mul_le_mul_of_nonneg_left hnorm (norm_nonneg u)
  have h3 : t ≤ u x := hx
  rw [ht] at h3
  linarith

end Reductions

end Limits

end ConvexFilter
