import ConvexFilters.LimitAlg

/-!
# Members of the algebra: vanishing at infinity, functionals, and the two indicators

WO-13, Part C; Section 3 of `paper/limits-algebra-note.tex`.

Three families of members of the algebra `mem_A` of `ConvexFilters/LimitAlg.lean`:

* `mem_A_of_tendsto_zero` (Proposition 3.1): a function tending to `0` along the cocompact
  filter converges along every maximal convex filter, with limit `0` at each non-principal
  one;
* `mem_A_comp_functional` (Proposition 3.2): `φ ∘ u` for a continuous `φ : EReal → ℝ` and a
  continuous linear functional `u`, with limit `φ (levVal F u)`.  The extended-real
  `levVal` of `ConvexFilters/SigmaCont.lean` is the right vehicle: it records the values
  `±∞` of the paper's `σ_F(u)` that `sig` cannot (see `notes/CONVENTIONS.md`, §1);
* `mem_A_indicator_gt`, `mem_A_indicator_ge` and `lim_indicator_table` (Proposition 3.3):
  the indicators of the open and the closed half-space, and the table of their limits,
  which reads off which of `u ∈ Dset F`, `u ∈ Mset F`, `-u ∈ Dset F` holds.

The technical core is `tendsto_coe_levVal`: along the generated filter, a continuous linear
functional converges in `[-∞, +∞]` to the extended support value, and
`exists_mem_relative_position`: relative to a level `c`, a maximal convex filter has a
member on which `u > c` throughout, or one on which `u < c` throughout, or one on which
`u = c` throughout.
-/

open Filter Topology

namespace ConvexFilter

namespace Limits

open ConvexFilter.Space

section Members

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- If `f` is constant on some member of `F`, it converges along `F` to that constant. -/
theorem hasLim_and_lim_of_eqOn {f : V → ℝ} {F : ConvexFilter V} {v : ℝ} {C : Set V}
    (hC : C ∈ F.carrier) (h : ∀ x ∈ C, f x = v) : HasLim f F ∧ lim f F = v := by
  have htend : Filter.Tendsto f (toFilter F) (nhds v) := by
    refine Filter.Tendsto.congr' ?_ (tendsto_const_nhds (x := v) (f := toFilter F))
    filter_upwards [mem_toFilter_of_mem_carrier hC] with x hx using (h x hx).symm
  exact ⟨⟨v, htend⟩, lim_eq_of_tendsto htend⟩

/-! ### Functions vanishing at infinity -/

end Members

section C0

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V] [FiniteDimensional ℝ V]

/-- **Proposition 3.1 of the note.** A function tending to `0` along the cocompact filter
lies in the algebra, and its limit along every non-principal maximal convex filter is `0`. -/
theorem mem_A_of_tendsto_zero {f : V → ℝ} (h : Filter.Tendsto f (Filter.cocompact V) (nhds 0)) :
    mem_A f ∧ ∀ F, IsMaximal F → (∀ p, F.carrier ≠ (principal p).carrier) → lim f F = 0 := by
  -- the limit is `0` along any non-principal maximal filter
  have key : ∀ F : ConvexFilter V, IsMaximal F → (∀ p, F.carrier ≠ (principal p).carrier) →
      Filter.Tendsto f (toFilter F) (nhds 0) := by
    intro F hF hnp
    rw [Metric.tendsto_nhds]
    intro ε hε
    have hmem : {x : V | dist (f x) 0 < ε} ∈ Filter.cocompact V :=
      h (Metric.ball_mem_nhds (0 : ℝ) hε)
    obtain ⟨K, hKcomp, hKsub⟩ := Filter.mem_cocompact.mp hmem
    obtain ⟨C, hC, hCK⟩ :=
      exists_mem_disjoint_of_not_principal hF hnp K hKcomp.isBounded
    refine Filter.eventually_of_mem (mem_toFilter_of_mem_carrier hC) fun x hx => ?_
    refine hKsub ?_
    intro hxK
    have : x ∈ C ∩ K := ⟨hx, hxK⟩
    rw [hCK] at this
    exact this
  refine ⟨fun F hF => ?_, fun F hF hnp => lim_eq_of_tendsto (key F hF hnp)⟩
  by_cases hnp : ∀ p, F.carrier ≠ (principal p).carrier
  · exact ⟨0, key F hF hnp⟩
  · push_neg at hnp
    obtain ⟨p, hp⟩ := hnp
    have hFp : F = principal p := ext_of_carrier_eq hp
    subst hFp
    exact hasLim_principal f p

end C0

/-! ### Continuous functions of a linear functional -/

section Functional

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- Along the filter generated by a maximal convex filter, a continuous linear functional
converges in `[-∞, +∞]` to the extended support value `levVal F u`. -/
theorem tendsto_coe_levVal {F : ConvexFilter V} (hF : IsMaximal F) (u : V →L[ℝ] ℝ) :
    Filter.Tendsto (fun x => ((u x : ℝ) : EReal)) (toFilter F) (nhds (levVal F u)) := by
  rcases levVal_cases F hF u with ⟨hlev, hval⟩ | ⟨hlev, hval⟩ | ⟨hu, hval⟩
  · -- support value `+∞`: every half-space `[u ≥ t]` belongs to `F`
    rw [hval, EReal.tendsto_nhds_top_iff_real]
    intro t
    have hmem : halfGE u (t + 1) ∈ F.carrier := by
      refine halfGE_of_not_halfLE hF fun hcon => ?_
      have : t + 1 ∈ lev F u := hcon
      rw [hlev] at this
      exact this
    filter_upwards [mem_toFilter_of_mem_carrier hmem] with x hx
    have hx' : t + 1 ≤ u x := hx
    exact_mod_cast lt_of_lt_of_le (by linarith) hx'
  · -- support value `-∞`: every half-space `[u ≤ t]` belongs to `F`
    rw [hval, EReal.tendsto_nhds_bot_iff_real]
    intro t
    have hmem : halfLE u (t - 1) ∈ F.carrier := by
      have : t - 1 ∈ lev F u := by rw [hlev]; exact Set.mem_univ _
      exact this
    filter_upwards [mem_toFilter_of_mem_carrier hmem] with x hx
    have hx' : u x ≤ t - 1 := hx
    exact_mod_cast lt_of_le_of_lt hx' (by linarith)
  · -- finite support value
    rw [hval]
    refine EReal.tendsto_coe.mpr ?_
    rw [Metric.tendsto_nhds]
    intro ε hε
    set c : ℝ := sig F u with hc
    have hup : halfLE u (c + ε / 2) ∈ F.carrier :=
      mem_lev_of_sig_lt hF hu (by linarith)
    have hdown : halfGE u (c - ε / 2) ∈ F.carrier := by
      refine halfGE_of_not_halfLE hF ?_
      exact not_mem_lev_of_lt_sig hF hu (by linarith)
    filter_upwards [mem_toFilter_of_mem_carrier (F.inter_mem hup hdown)] with x hx
    obtain ⟨hx1, hx2⟩ := hx
    have h1 : u x ≤ c + ε / 2 := hx1
    have h2 : c - ε / 2 ≤ u x := hx2
    rw [Real.dist_eq, abs_lt]
    constructor <;> linarith

/-- **Proposition 3.2 of the note.** For a continuous `φ : [-∞, +∞] → ℝ` and a continuous
linear functional `u`, the function `x ↦ φ (u x)` lies in the algebra, with limit
`φ (levVal F u)` at every maximal convex filter. -/
theorem mem_A_comp_functional (u : V →L[ℝ] ℝ) {φ : EReal → ℝ} (hφ : Continuous φ) :
    mem_A (fun x => φ (u x)) ∧
      ∀ F, IsMaximal F → lim (fun x => φ (u x)) F = φ (levVal F u) := by
  have key : ∀ F : ConvexFilter V, IsMaximal F →
      Filter.Tendsto (fun x => φ ((u x : ℝ) : EReal)) (toFilter F) (nhds (φ (levVal F u))) :=
    fun F hF => (hφ.tendsto _).comp (tendsto_coe_levVal hF u)
  exact ⟨fun F hF => ⟨_, key F hF⟩, fun F hF => lim_eq_of_tendsto (key F hF)⟩

end Functional

/-! ### The two indicators -/

section Indicators

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- A maximal convex filter with `u ∈ Dset F` has a member on which `u` exceeds its support
number. -/
theorem exists_mem_gt_of_mem_Dset {F : ConvexFilter V} (hF : IsMaximal F) {u : V →L[ℝ] ℝ}
    (hu : u ∈ Dset F) : ∃ C ∈ F.carrier, ∀ x ∈ C, sig F u < u x := by
  have hnot : halfLE u (sig F u) ∉ F.carrier := hu.2
  obtain ⟨D, hD, hdisj⟩ :=
    (isMaximal_iff F).mp hF (isClosed_halfLE u (sig F u)) (convex_halfLE u (sig F u)) hnot
  refine ⟨D, hD, fun x hx => ?_⟩
  by_contra hcon
  push_neg at hcon
  have : x ∈ halfLE u (sig F u) ∩ D := ⟨hcon, hx⟩
  rw [hdisj] at this
  exact this

/-- A maximal convex filter with `-u ∈ Dset F` has a member on which `u` stays below the
support number of `u`. -/
theorem exists_mem_lt_of_neg_mem_Dset {F : ConvexFilter V} (hF : IsMaximal F) {u : V →L[ℝ] ℝ}
    (hu : u ∈ Nset F) (hnu : -u ∈ Dset F) : ∃ C ∈ F.carrier, ∀ x ∈ C, u x < sig F u := by
  obtain ⟨C, hC, hCx⟩ := exists_mem_gt_of_mem_Dset hF hnu
  refine ⟨C, hC, fun x hx => ?_⟩
  have h := hCx x hx
  rw [sig_neg hF hu] at h
  have : (-u) x = -(u x) := rfl
  rw [this] at h
  linarith

/-- **The three relative positions.** For a maximal convex filter, a functional and a level,
one of three things happens: a member on which `u > c`, a member on which `u < c`, or a
member on which `u = c`. -/
theorem exists_mem_relative_position {F : ConvexFilter V} (hF : IsMaximal F) (u : V →L[ℝ] ℝ)
    (c : ℝ) :
    (∃ C ∈ F.carrier, ∀ x ∈ C, c < u x) ∨ (∃ C ∈ F.carrier, ∀ x ∈ C, u x < c) ∨
      (∃ C ∈ F.carrier, ∀ x ∈ C, u x = c) := by
  rcases lt_trichotomy (levVal F u) (c : EReal) with hlt | heq | hgt
  · -- below the level: a half-space `[u ≤ c']` with `c' < c` belongs to `F`
    obtain ⟨c', hc1, hc2⟩ := EReal.lt_iff_exists_real_btwn.mp hlt
    have hnot : halfGE u c' ∉ F.carrier := notMem_halfGE_of_levVal_lt hF hc1
    have hmem : halfLE u c' ∈ F.carrier := (halfLE_or_halfGE hF u c').resolve_right hnot
    have hc2' : c' < c := by exact_mod_cast hc2
    exact Or.inr (Or.inl ⟨halfLE u c', hmem, fun x hx => lt_of_le_of_lt hx hc2'⟩)
  · -- at the level: the trichotomy of the invariants
    have hu : u ∈ Nset F := by
      refine (mem_Nset_iff_levVal_ne hF u).mpr ⟨?_, ?_⟩
      · rw [heq]; exact EReal.coe_ne_top c
      · rw [heq]; exact EReal.coe_ne_bot c
    have hsig : sig F u = c := by
      have := heq
      rw [levVal_of_mem_Nset hF hu] at this
      exact_mod_cast this
    rcases mem_Qset_or_neg_or_Mset hF u with hQ | hQ | hM
    · have hD : u ∈ Dset F := by
        rcases (Qset_eq_Eset_union_Dset hF ▸ hQ : u ∈ Eset F ∪ Dset F) with hE | hD
        · exact absurd hE hu.1
        · exact hD
      obtain ⟨C, hC, hCx⟩ := exists_mem_gt_of_mem_Dset hF hD
      exact Or.inl ⟨C, hC, fun x hx => hsig ▸ hCx x hx⟩
    · have hnu : -u ∈ Nset F := Nset_neg hu
      have hD : -u ∈ Dset F := by
        rcases (Qset_eq_Eset_union_Dset hF ▸ hQ : -u ∈ Eset F ∪ Dset F) with hE | hD
        · exact absurd hE hnu.1
        · exact hD
      obtain ⟨C, hC, hCx⟩ := exists_mem_lt_of_neg_mem_Dset hF hu hD
      exact Or.inr (Or.inl ⟨C, hC, fun x hx => hsig ▸ hCx x hx⟩)
    · obtain ⟨t, ht⟩ := hM
      have hts : t = sig F u := (sig_eq_of_hyperplane_mem ht).symm
      refine Or.inr (Or.inr ⟨hyperplane u t, ht, fun x hx => ?_⟩)
      have : u x = t := hx
      rw [this, hts, hsig]
  · -- above the level: a half-space `[u ≥ c']` with `c < c'` belongs to `F`
    obtain ⟨c', hc1, hc2⟩ := EReal.lt_iff_exists_real_btwn.mp hgt
    have hnot : halfLE u c' ∉ F.carrier := notMem_halfLE_of_lt_levVal hF hc2
    have hmem : halfGE u c' ∈ F.carrier := halfGE_of_not_halfLE hF hnot
    have hc1' : c < c' := by exact_mod_cast hc1
    exact Or.inl ⟨halfGE u c', hmem, fun x hx => lt_of_lt_of_le hc1' hx⟩

/-- The indicator of an open half-space is `1` on a set where `u > c`. -/
theorem indicator_gt_eq_one {u : V →L[ℝ] ℝ} {c : ℝ} {x : V} (hx : c < u x) :
    Set.indicator {x : V | c < u x} (1 : V → ℝ) x = 1 := Set.indicator_of_mem hx 1

theorem indicator_gt_eq_zero {u : V →L[ℝ] ℝ} {c : ℝ} {x : V} (hx : ¬ c < u x) :
    Set.indicator {x : V | c < u x} (1 : V → ℝ) x = 0 := Set.indicator_of_notMem hx 1

theorem indicator_ge_eq_one {u : V →L[ℝ] ℝ} {c : ℝ} {x : V} (hx : c ≤ u x) :
    Set.indicator {x : V | c ≤ u x} (1 : V → ℝ) x = 1 := Set.indicator_of_mem hx 1

theorem indicator_ge_eq_zero {u : V →L[ℝ] ℝ} {c : ℝ} {x : V} (hx : ¬ c ≤ u x) :
    Set.indicator {x : V | c ≤ u x} (1 : V → ℝ) x = 0 := Set.indicator_of_notMem hx 1

/-- **Proposition 3.3 of the note, membership for the open half-space.**  The hypothesis
`u ≠ 0` is not needed for the proof; it is kept as the contract specifies it (see
`notes/CONVENTIONS.md`, §6). -/
theorem mem_A_indicator_gt (u : V →L[ℝ] ℝ) (hu : u ≠ 0) (c : ℝ) :
    mem_A (Set.indicator {x : V | c < u x} 1) := by
  intro F hF
  rcases exists_mem_relative_position hF u c with ⟨C, hC, hCx⟩ | ⟨C, hC, hCx⟩ | ⟨C, hC, hCx⟩
  · exact (hasLim_and_lim_of_eqOn hC fun x hx => indicator_gt_eq_one (hCx x hx)).1
  · exact (hasLim_and_lim_of_eqOn hC fun x hx =>
      indicator_gt_eq_zero (not_lt.mpr (hCx x hx).le)).1
  · exact (hasLim_and_lim_of_eqOn hC fun x hx =>
      indicator_gt_eq_zero (by rw [hCx x hx]; exact lt_irrefl c)).1

/-- **Proposition 3.3 of the note, membership for the closed half-space.**  The hypothesis
`u ≠ 0` is not needed for the proof; it is kept as the contract specifies it. -/
theorem mem_A_indicator_ge (u : V →L[ℝ] ℝ) (hu : u ≠ 0) (c : ℝ) :
    mem_A (Set.indicator {x : V | c ≤ u x} 1) := by
  intro F hF
  rcases exists_mem_relative_position hF u c with ⟨C, hC, hCx⟩ | ⟨C, hC, hCx⟩ | ⟨C, hC, hCx⟩
  · exact (hasLim_and_lim_of_eqOn hC fun x hx => indicator_ge_eq_one (hCx x hx).le).1
  · exact (hasLim_and_lim_of_eqOn hC fun x hx =>
      indicator_ge_eq_zero (not_le.mpr (hCx x hx))).1
  · exact (hasLim_and_lim_of_eqOn hC fun x hx =>
      indicator_ge_eq_one (le_of_eq (hCx x hx).symm)).1

open Classical in
/-- **Proposition 3.3 of the note.** At a functional whose extended support value is the
finite level `c`, the pair of limits of the two indicators reads off which of the three
alternatives `u ∈ Dset F`, `u ∈ Mset F`, `-u ∈ Dset F` holds.  The hypothesis `u ≠ 0` is
not needed for the proof; it is kept as the contract specifies it. -/
theorem lim_indicator_table {F : ConvexFilter V} (hF : IsMaximal F) (u : V →L[ℝ] ℝ)
    (hu : u ≠ 0) {c : ℝ} (hc : levVal F u = (c : EReal)) :
    (lim (Set.indicator {x : V | c < u x} 1) F, lim (Set.indicator {x : V | c ≤ u x} 1) F)
      = if u ∈ Dset F then (1, 1) else if u ∈ Mset F then (0, 1) else (0, 0) := by
  have hun : u ∈ Nset F := by
    refine (mem_Nset_iff_levVal_ne hF u).mpr ⟨?_, ?_⟩
    · rw [hc]; exact EReal.coe_ne_top c
    · rw [hc]; exact EReal.coe_ne_bot c
  have hsig : sig F u = c := by
    have := hc
    rw [levVal_of_mem_Nset hF hun] at this
    exact_mod_cast this
  by_cases hD : u ∈ Dset F
  · rw [if_pos hD]
    obtain ⟨C, hC, hCx⟩ := exists_mem_gt_of_mem_Dset hF hD
    have hgt : ∀ x ∈ C, c < u x := fun x hx => hsig ▸ hCx x hx
    have h1 := (hasLim_and_lim_of_eqOn hC fun x hx => indicator_gt_eq_one (hgt x hx)).2
    have h2 := (hasLim_and_lim_of_eqOn hC fun x hx => indicator_ge_eq_one (hgt x hx).le).2
    rw [h1, h2]
  · rw [if_neg hD]
    by_cases hM : u ∈ Mset F
    · rw [if_pos hM]
      obtain ⟨t, ht⟩ := hM
      have hts : t = c := by rw [← hsig, sig_eq_of_hyperplane_mem ht]
      subst hts
      have heq : ∀ x ∈ hyperplane u t, u x = t := fun _ hx => hx
      have h1 := (hasLim_and_lim_of_eqOn ht fun x hx =>
        indicator_gt_eq_zero (by rw [heq x hx]; exact lt_irrefl t)).2
      have h2 := (hasLim_and_lim_of_eqOn ht fun x hx =>
        indicator_ge_eq_one (le_of_eq (heq x hx).symm)).2
      rw [h1, h2]
    · rw [if_neg hM]
      -- the remaining case is `-u ∈ Dset F`
      have hnQ : -u ∈ Qset F := by
        rcases mem_Qset_or_neg_or_Mset hF u with hQ | hQ | hQ
        · exfalso
          rcases (Qset_eq_Eset_union_Dset hF ▸ hQ : u ∈ Eset F ∪ Dset F) with hE | hD'
          · exact hun.1 hE
          · exact hD hD'
        · exact hQ
        · exact absurd hQ hM
      have hnu : -u ∈ Nset F := Nset_neg hun
      have hnD : -u ∈ Dset F := by
        rcases (Qset_eq_Eset_union_Dset hF ▸ hnQ : -u ∈ Eset F ∪ Dset F) with hE | hD'
        · exact absurd hE hnu.1
        · exact hD'
      obtain ⟨C, hC, hCx⟩ := exists_mem_lt_of_neg_mem_Dset hF hun hnD
      have hlt : ∀ x ∈ C, u x < c := fun x hx => hsig ▸ hCx x hx
      have h1 := (hasLim_and_lim_of_eqOn hC fun x hx =>
        indicator_gt_eq_zero (not_lt.mpr (hlt x hx).le)).2
      have h2 := (hasLim_and_lim_of_eqOn hC fun x hx =>
        indicator_ge_eq_zero (not_le.mpr (hlt x hx))).2
      rw [h1, h2]

end Indicators

end Limits

end ConvexFilter
