import ConvexFilters.LimitRidge
import ConvexFilters.Boundary

/-!
# Corollary 10.5: the algebra is strictly larger than the continuous functions on `hM(ℝ²)`

WO-14; Corollary 10.5 of `paper/maximal-convex-filters.tex` (`cor:strictly`).

The algebra `𝒜_b(ℝ²)` of bounded functions converging along every maximal convex filter
properly contains the restrictions to `ℝ²` of the continuous functions on the maximal
Hausdorff quotient `hM(ℝ²) = T2Quotient (MaxFilter (ℝ × ℝ))`.

## Contents

* `tendsto_prin_toFilter`: the principal filters converge, along the filter generated by a
  maximal convex filter `F`, to the point `F` of `MaxFilter V`.  This is the step that uses
  the maximality criterion `isMaximal_iff`: a closed convex `C` not in `F` is disjoint from
  a member of `F`, and that member is exactly a set on which `prin` avoids the subbasic
  closed set `Vset C`.
* `mem_A_comp_prinQ`, `isBounded_comp_prinQ`: hence every restriction to `ℝ²` (indeed to
  `V`) of a continuous function on the quotient lies in the algebra, and is bounded because
  the quotient is compact.  This is the inclusion half of Corollary 10.5.
* `not_exists_continuous_extension_ridge`: the ridge of Lemma 10.4 (`LimitRidge.lean`) is
  not such a restriction.  This is the properness half.
* `restrictionsOfContinuous_ssubset_A_b`: the two together, in comparative form.

## The argument, and how it differs from the sketch in the work order

The work order proposes: for `ε > 0` the set `{|g| ≥ ε}` is compact and, by the vanishing of
`g` off the image of the plane, contained in the open image `Set.range prinQ`; then transport
compactness back along the principal embedding to conclude `ridge ∈ C₀(ℝ²)`, contradicting
`not_tendsto_cocompact_ridge`.  The transport step needs `prinQ` to be an embedding — a
homeomorphism onto its image — and `T2Quotient.mk` is in general only a quotient map, so
that is exactly the step flagged as in need of checking.

It is not needed.  What the transport step is used for is: *a point of `hM(ℝ²)` at which the
plane accumulates along the cocompact filter is not in the image of the plane*.  That is
proved here directly, as `notMem_range_prinQ_of_clusterPt`, from the continuous coordinates
`levQ fstCLM` and `levQ sndCLM` of `Boundary.lean`, which restrict to the two coordinate
functions on the image of the plane: a cluster point lying at `prinQ q` would force the plane
to meet, cofrequently along the cocompact filter, the box of side `2` around `q`, which the
cocompact filter forbids.  No embedding property of `prinQ` is used, and neither is the
openness of `Set.range prinQ`; the compactness used is that of `hM(ℝ²)` itself
(`exists_clusterPt_of_compactSpace`), which is Part A of `Boundary.lean`.

The rest of the sketch is unchanged: `lim_ridge_eq_zero` forces `g` to vanish at every class
of a non-principal filter (`eq_zero_of_notMem_range_prinQ`), a cluster point along the
cocompact filter of a level set `{|ridge| ≥ ε}` is such a class, and so `ridge` tends to `0`
along `Filter.cocompact`, contradicting `not_tendsto_cocompact_ridge`.
-/

open Filter Topology

namespace ConvexFilter

namespace Limits

open Space

/-! ### Principal filters converge to a maximal filter along the filter it generates -/

section General

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- **The convergence behind Corollary 10.5.** Along the filter `toFilter F` generated by a
maximal convex filter `F`, the principal filters `prin p` converge to `F` as points of
`MaxFilter V`.

The subbasic open neighbourhoods of `F` are the sets `(Vset C)ᶜ` with `C` closed, convex and
not a member of `F`; the maximality criterion `isMaximal_iff` produces a member `D` of `F`
disjoint from such a `C`, and `prin p ∉ Vset C` for every `p ∈ D`. -/
theorem tendsto_prin_toFilter {F : ConvexFilter V} (hF : IsMaximal F) :
    Filter.Tendsto (prin : V → MaxFilter V) (toFilter F) (nhds (⟨F, hF⟩ : MaxFilter V)) := by
  set Fpt : MaxFilter V := ⟨F, hF⟩
  have hn : nhds Fpt = ⨅ s ∈ {s : Set (MaxFilter V) | Fpt ∈ s ∧ s ∈ subbase V}, 𝓟 s :=
    TopologicalSpace.nhds_generateFrom
  rw [hn, Filter.tendsto_iInf]
  intro s
  rw [Filter.tendsto_iInf]
  rintro ⟨hs, C, hcl, hcv, rfl⟩
  rw [Filter.tendsto_principal]
  have hCF : C ∉ F.carrier := hs
  obtain ⟨D, hD, hdisj⟩ := (isMaximal_iff F).mp hF hcl hcv hCF
  refine Filter.mem_of_superset (mem_toFilter_of_mem_carrier hD) ?_
  intro p hp hmem
  have hpC : p ∈ C := (mem_principal_iff.mp hmem).2.2
  have : p ∈ C ∩ D := ⟨hpC, hp⟩
  rw [hdisj] at this
  exact this

/-- The same convergence in the maximal Hausdorff quotient. -/
theorem tendsto_prinQ_toFilter {F : ConvexFilter V} (hF : IsMaximal F) :
    Filter.Tendsto (prinQ : V → T2Quotient (MaxFilter V)) (toFilter F)
      (nhds (T2Quotient.mk (⟨F, hF⟩ : MaxFilter V))) :=
  ((T2Quotient.continuous_mk _).tendsto _).comp (tendsto_prin_toFilter hF)

/-- **Corollary 10.5, the inclusion.** The restriction to `V` of a continuous function on
the maximal Hausdorff quotient converges along every maximal convex filter, so it lies in
the algebra `𝒜`. -/
theorem mem_A_comp_prinQ {g : T2Quotient (MaxFilter V) → ℝ} (hg : Continuous g) :
    mem_A (fun p : V => g (prinQ p)) :=
  fun F hF => ⟨g (T2Quotient.mk (⟨F, hF⟩ : MaxFilter V)),
    (hg.tendsto _).comp (tendsto_prinQ_toFilter hF)⟩

/-- The limit of such a restriction along `F` is the value of `g` at the class of `F`. -/
theorem lim_comp_prinQ {g : T2Quotient (MaxFilter V) → ℝ} (hg : Continuous g)
    {F : ConvexFilter V} (hF : IsMaximal F) :
    lim (fun p : V => g (prinQ p)) F = g (T2Quotient.mk (⟨F, hF⟩ : MaxFilter V)) :=
  lim_eq_of_tendsto ((hg.tendsto _).comp (tendsto_prinQ_toFilter hF))

/-- Such a restriction is bounded: the quotient is compact. -/
theorem isBounded_comp_prinQ {g : T2Quotient (MaxFilter V) → ℝ} (hg : Continuous g) :
    ∃ M : ℝ, ∀ p : V, |g (prinQ p)| ≤ M := by
  obtain ⟨M, hM⟩ := (isCompact_univ (X := T2Quotient (MaxFilter V))).exists_bound_of_continuousOn
    hg.continuousOn
  exact ⟨M, fun p => by simpa [Real.norm_eq_abs] using hM (prinQ p) (Set.mem_univ _)⟩

end General

/-! ### A continuous extension of the ridge would vanish off the image of the plane -/

section Plane

variable {g : T2Quotient (MaxFilter (ℝ × ℝ)) → ℝ}

/-- **Step 1.** If `g` restricts to the ridge on the image of the plane, then `g` vanishes at
the class of every non-principal maximal convex filter: the principal filters converge to
that class along `toFilter F`, while the ridge converges to `0` there by
`lim_ridge_eq_zero`. -/
theorem eq_zero_of_not_principal (hg : Continuous g) (hgr : ∀ p : ℝ × ℝ, g (prinQ p) = ridge p)
    {F : ConvexFilter (ℝ × ℝ)} (hF : IsMaximal F)
    (hnp : ∀ p, F.carrier ≠ (principal p).carrier) :
    g (T2Quotient.mk (⟨F, hF⟩ : MaxFilter (ℝ × ℝ))) = 0 := by
  have h1 : Filter.Tendsto ridge (toFilter F)
      (nhds (g (T2Quotient.mk (⟨F, hF⟩ : MaxFilter (ℝ × ℝ))))) := by
    have h := (hg.tendsto _).comp (tendsto_prinQ_toFilter hF)
    rwa [show (g ∘ (prinQ : (ℝ × ℝ) → T2Quotient (MaxFilter (ℝ × ℝ)))) = ridge from
      funext hgr] at h
  have h2 : Filter.Tendsto ridge (toFilter F) (nhds 0) := by
    have h := tendsto_lim (mem_A_ridge F hF)
    rwa [lim_ridge_eq_zero hF hnp] at h
  exact tendsto_nhds_unique h1 h2

/-- **Step 1, in the form used.** Such a `g` vanishes off the image of the plane: a class
outside the image is the class of a maximal filter that is not principal. -/
theorem eq_zero_of_notMem_range_prinQ (hg : Continuous g)
    (hgr : ∀ p : ℝ × ℝ, g (prinQ p) = ridge p) {x : T2Quotient (MaxFilter (ℝ × ℝ))}
    (hx : x ∉ Set.range (prinQ : (ℝ × ℝ) → T2Quotient (MaxFilter (ℝ × ℝ)))) : g x = 0 := by
  obtain ⟨F, rfl⟩ := T2Quotient.surjective_mk (MaxFilter (ℝ × ℝ)) x
  have hnp : ∀ p, F.1.carrier ≠ (principal p).carrier := by
    intro p hp
    refine hx ⟨p, ?_⟩
    have : F = prin p := Subtype.ext (ext_of_carrier_eq hp)
    rw [prinQ, this]
  simpa using eq_zero_of_not_principal hg hgr F.2 hnp

/-! ### Points where the plane accumulates at infinity are not in the image of the plane -/

/-- **The step that replaces the embedding property of `prinQ`.** A cluster point, in the
maximal Hausdorff quotient, of the image of a filter refining the cocompact filter of the
plane does not lie in the image of the plane.

If the cluster point were `prinQ q`, then the open set cut out by
`levQ fstCLM ∈ (q.1 - 1, q.1 + 1)` and `levQ sndCLM ∈ (q.2 - 1, q.2 + 1)` would be a
neighbourhood of it, and the classes `prinQ p` meeting it frequently along the filter have
`p` in the closed box of side `2` around `q`; but the complement of that compact box belongs
to the cocompact filter, hence to the filter. -/
theorem notMem_range_prinQ_of_clusterPt {L : Filter (ℝ × ℝ)} (hL : L ≤ Filter.cocompact (ℝ × ℝ))
    {x : T2Quotient (MaxFilter (ℝ × ℝ))} (hx : ClusterPt x (Filter.map prinQ L)) :
    x ∉ Set.range (prinQ : (ℝ × ℝ) → T2Quotient (MaxFilter (ℝ × ℝ))) := by
  rintro ⟨q, rfl⟩
  set W : Set (T2Quotient (MaxFilter (ℝ × ℝ))) :=
    (levQ fstCLM) ⁻¹' (Set.Ioo ((q.1 - 1 : ℝ) : EReal) ((q.1 + 1 : ℝ) : EReal)) ∩
      (levQ sndCLM) ⁻¹' (Set.Ioo ((q.2 - 1 : ℝ) : EReal) ((q.2 + 1 : ℝ) : EReal))
  have hWopen : IsOpen W :=
    ((continuous_levQ _).isOpen_preimage _ isOpen_Ioo).inter
      ((continuous_levQ _).isOpen_preimage _ isOpen_Ioo)
  have hqW : prinQ q ∈ W := by
    constructor <;>
      simp only [Set.mem_preimage, levQ_prinQ, Set.mem_Ioo, EReal.coe_lt_coe_iff] <;>
      constructor <;> simp
  have hfreq : ∃ᶠ p in L, prinQ p ∈ W := by
    have := clusterPt_iff_frequently.mp hx W (hWopen.mem_nhds hqW)
    rwa [Filter.frequently_map] at this
  set box : Set (ℝ × ℝ) := Set.Icc (q.1 - 1) (q.1 + 1) ×ˢ Set.Icc (q.2 - 1) (q.2 + 1)
  have hboxcompact : IsCompact box := isCompact_Icc.prod isCompact_Icc
  have hout : ∀ᶠ p in L, p ∉ box := hL hboxcompact.compl_mem_cocompact
  obtain ⟨p, hpW, hpbox⟩ := (hfreq.and_eventually hout).exists
  refine hpbox ?_
  obtain ⟨h1, h2⟩ := hpW
  simp only [Set.mem_preimage, levQ_prinQ, Set.mem_Ioo, EReal.coe_lt_coe_iff] at h1 h2
  exact ⟨⟨h1.1.le, h1.2.le⟩, ⟨h2.1.le, h2.2.le⟩⟩

/-! ### The corollary -/

/-- **Steps 2–4.** A continuous extension of the ridge to the quotient would put the ridge
in `C₀(ℝ²)`.

Given `ε > 0` for which `{|ridge| ≥ ε}` is cofrequent at infinity, the filter
`L = cocompact ⊓ 𝓟 {|ridge| ≥ ε}` is proper; the quotient is compact, so the image of `L`
has a cluster point `x`, which is off the image of the plane by
`notMem_range_prinQ_of_clusterPt`, hence has `g x = 0` by `eq_zero_of_notMem_range_prinQ`;
but `g x` is also a cluster point of the values of the ridge along `L`, all of which are at
distance at least `ε` from `0`. -/
theorem tendsto_cocompact_ridge_of_continuous_extension (hg : Continuous g)
    (hgr : ∀ p : ℝ × ℝ, g (prinQ p) = ridge p) :
    Filter.Tendsto ridge (Filter.cocompact (ℝ × ℝ)) (nhds 0) := by
  rw [Metric.tendsto_nhds]
  intro ε hε
  by_contra hcon
  rw [Filter.not_eventually] at hcon
  set L : Filter (ℝ × ℝ) :=
    Filter.cocompact (ℝ × ℝ) ⊓ 𝓟 {p : ℝ × ℝ | ¬ dist (ridge p) 0 < ε}
  haveI : L.NeBot := Filter.frequently_iff_neBot.mp hcon
  obtain ⟨x, hx⟩ := exists_clusterPt_of_compactSpace (Filter.map prinQ L)
  have hxr : x ∉ Set.range (prinQ : (ℝ × ℝ) → T2Quotient (MaxFilter (ℝ × ℝ))) :=
    notMem_range_prinQ_of_clusterPt inf_le_left hx
  have hgx : g x = 0 := eq_zero_of_notMem_range_prinQ hg hgr hxr
  -- `g x` is a cluster point of the values of the ridge along `L`
  have hmapeq : Filter.map g (Filter.map prinQ L) = Filter.map ridge L := by
    rw [Filter.map_map]
    exact congrArg (fun f => Filter.map f L) (funext hgr)
  have hc2 : ClusterPt (g x) (Filter.map ridge L) := by
    have := hx.map hg.continuousAt Filter.tendsto_map
    rwa [hmapeq] at this
  -- all those values are at distance at least `ε` from `0`
  set T : Set ℝ := {t : ℝ | ε ≤ dist t 0} with hT
  have hTclosed : IsClosed T := isClosed_le continuous_const (continuous_id.dist continuous_const)
  have hle : Filter.map ridge L ≤ 𝓟 T := by
    rw [Filter.le_principal_iff, Filter.mem_map]
    refine Filter.mem_of_superset (Filter.mem_inf_of_right (Filter.mem_principal_self _)) ?_
    intro p hp
    exact not_lt.mp hp
  have : g x ∈ closure T := mem_closure_iff_clusterPt.mpr (hc2.mono hle)
  rw [hTclosed.closure_eq, hT, Set.mem_setOf_eq, hgx] at this
  simp at this
  linarith

/-- **Corollary 10.5, the properness.** The ridge is not the restriction to `ℝ²` of a
continuous function on the maximal Hausdorff quotient `hM(ℝ²)`. -/
theorem not_exists_continuous_extension_ridge :
    ¬ ∃ g : T2Quotient (MaxFilter (ℝ × ℝ)) → ℝ, Continuous g ∧
        ∀ p : ℝ × ℝ, g (T2Quotient.mk ⟨principal p, principal_isMaximal p⟩) = ridge p := by
  rintro ⟨g, hg, hgr⟩
  exact not_tendsto_cocompact_ridge (tendsto_cocompact_ridge_of_continuous_extension hg hgr)

/-- **Corollary 10.5, comparative form.** There is a member of the algebra — the ridge — that
is not the restriction to `ℝ²` of a continuous function on `hM(ℝ²)`. -/
theorem exists_mem_A_not_continuous_on_quotient :
    ∃ f : (ℝ × ℝ) → ℝ, mem_A f ∧
      ¬ ∃ g : T2Quotient (MaxFilter (ℝ × ℝ)) → ℝ, Continuous g ∧
          ∀ p : ℝ × ℝ, g (T2Quotient.mk ⟨principal p, principal_isMaximal p⟩) = f p :=
  ⟨ridge, mem_A_ridge, not_exists_continuous_extension_ridge⟩

/-! ### "Properly contains", as an inclusion of sets of functions -/

/-- The restrictions to `V` of the continuous functions on the maximal Hausdorff quotient of
`MaxFilter V`. -/
def restrictionsOfContinuous (V : Type*) [NormedAddCommGroup V] [NormedSpace ℝ V] :
    Set (V → ℝ) :=
  {f : V → ℝ | ∃ g : T2Quotient (MaxFilter V) → ℝ, Continuous g ∧ ∀ p : V, g (prinQ p) = f p}

/-- The algebra `𝒜_b`: the bounded functions converging along every maximal convex filter. -/
def A_b (V : Type*) [NormedAddCommGroup V] [NormedSpace ℝ V] : Set (V → ℝ) :=
  {f : V → ℝ | mem_A f ∧ ∃ M : ℝ, ∀ p : V, |f p| ≤ M}

theorem ridge_mem_A_b : ridge ∈ A_b (ℝ × ℝ) := by
  refine ⟨mem_A_ridge, 1, fun p => ?_⟩
  have h0 : 0 ≤ ridge p := le_max_left _ _
  have h1 : ridge p ≤ 1 := by
    refine max_le (by norm_num) ?_
    have := abs_nonneg (p.2 - p.1 ^ 2)
    linarith
  rw [abs_of_nonneg h0]
  exact h1

theorem ridge_notMem_restrictionsOfContinuous : ridge ∉ restrictionsOfContinuous (ℝ × ℝ) :=
  not_exists_continuous_extension_ridge

/-- **Corollary 10.5.** The algebra `𝒜_b(ℝ²)` properly contains the restrictions to `ℝ²` of
the continuous functions on `hM(ℝ²)`. -/
theorem restrictionsOfContinuous_ssubset_A_b :
    restrictionsOfContinuous (ℝ × ℝ) ⊂ A_b (ℝ × ℝ) := by
  constructor
  · rintro f ⟨g, hg, hgf⟩
    have hfeq : (fun p : ℝ × ℝ => g (prinQ p)) = f := funext hgf
    obtain ⟨M, hM⟩ := isBounded_comp_prinQ (V := ℝ × ℝ) hg
    exact ⟨hfeq ▸ mem_A_comp_prinQ hg, M, fun p => hfeq ▸ hM p⟩
  · intro hsub
    exact ridge_notMem_restrictionsOfContinuous (hsub ridge_mem_A_b)

end Plane

end Limits

end ConvexFilter
