import ConvexFilters.Extension
import ConvexFilters.Invariants

/-!
# An infinite-dimensional maximal convex filter with empty flat (Remark 8.7)

Remark 8.7 observes that the finite-dimensional theory does not survive verbatim in
infinite dimensions: on `ℓ²` there is a maximal convex filter whose flat is empty, so no
point realizes the support number.

The example is the antitone family of closed convex sets

`S n = {x | ∀ k ≤ n, x k = 1}`,

each nonempty (truncate the constant sequence `1`), with empty intersection (the constant
sequence `1` is not square-summable). Any maximal convex filter containing all of them
sees every coordinate functional in `Mset`, with support value `1`, and therefore has no
point at which all functionals of `Nset` attain their support values.

`Defs.lean`, `Basic.lean`, `Levels.lean` and `Invariants.lean` carry no
finite-dimensionality hypothesis, so `Mset`, `Nset` and `sig` are all available here.
`Aset` is defined in `Flat.lean`, which does assume finite-dimensionality; the conclusion
is therefore stated directly as the emptiness of `{x | ∀ u ∈ Nset F, u x = sig F u}`, which
is the definition `Aset` would unfold to.
-/

open scoped ENNReal

namespace ConvexFilter

namespace RemarkInfinite

/-- The ambient space of the example: real `ℓ²`. -/
abbrev L2 := lp (fun _ : ℕ => ℝ) 2

/-- The `k`-th coordinate functional on `ℓ²`, continuous with norm at most one. -/
noncomputable def coordCLM (k : ℕ) : L2 →L[ℝ] ℝ :=
  LinearMap.mkContinuous
    { toFun := fun x => x k
      map_add' := fun x y => by simp
      map_smul' := fun c x => by simp } 1
    (fun x => by simpa using lp.norm_apply_le_norm (by norm_num) x k)

@[simp] theorem coordCLM_apply (k : ℕ) (x : L2) : coordCLM k x = x k := rfl

/-- The `n`-th member of the base: the sequences whose first `n + 1` coordinates are `1`. -/
def S (n : ℕ) : Set L2 := {x : L2 | ∀ k ≤ n, x k = 1}

theorem isClosed_S (n : ℕ) : IsClosed (S n) := by
  have hEq : S n = ⋂ k, ⋂ (_ : k ≤ n), {x : L2 | coordCLM k x = 1} := by
    ext x
    simp only [S, Set.mem_setOf_eq, Set.mem_iInter, coordCLM_apply]
  rw [hEq]
  exact isClosed_iInter fun k => isClosed_iInter fun _ =>
    isClosed_eq (coordCLM k).continuous continuous_const

theorem convex_S (n : ℕ) : Convex ℝ (S n) := by
  intro x hx y hy a b ha hb hab k hk
  have hxk : coordCLM k x = 1 := hx k hk
  have hyk : coordCLM k y = 1 := hy k hk
  have : coordCLM k (a • x + b • y) = a * coordCLM k x + b * coordCLM k y := by
    simp
  have hval : coordCLM k (a • x + b • y) = 1 := by
    rw [this, hxk, hyk, mul_one, mul_one, hab]
  exact hval

theorem S_nonempty (n : ℕ) : (S n).Nonempty := by
  have hmem : Memℓp (fun i : ℕ => if i ≤ n then (1 : ℝ) else 0) 2 := by
    apply memℓp_gen
    apply summable_of_ne_finset_zero (s := Finset.range (n + 1))
    intro b hb
    simp only [Finset.mem_range, not_lt] at hb
    have hbn : ¬ b ≤ n := by omega
    simp [hbn]
  refine ⟨⟨fun i : ℕ => if i ≤ n then (1 : ℝ) else 0, hmem⟩, ?_⟩
  intro k hk
  show (if k ≤ n then (1 : ℝ) else 0) = 1
  simp [hk]

theorem S_antitone : Antitone S := by
  intro m n hmn x hx k hk
  exact hx k (le_trans hk hmn)

/-- A square-summable sequence cannot be constantly `1`. -/
theorem not_all_coords_one (x : L2) (h : ∀ k, x k = 1) : False := by
  have hsum : Summable (fun i : ℕ => ‖x i‖ ^ (2 : ℝ)) := by
    have hx := lp.memℓp x
    rw [memℓp_gen_iff (by norm_num)] at hx
    simpa using hx
  simp only [h] at hsum
  norm_num at hsum
  exact one_ne_zero ((summable_const_iff (1 : ℝ)).1 hsum)

theorem iInter_S_eq_empty : (⋂ n, S n) = ∅ := by
  rw [Set.eq_empty_iff_forall_notMem]
  intro x hx
  simp only [Set.mem_iInter] at hx
  exact not_all_coords_one x fun k => hx k k le_rfl

/-- The convex filter generated by the base `S`. -/
noncomputable def SBase : ConvexFilter L2 := ofAntitoneBase S S_nonempty S_antitone

/-- A maximal convex filter containing every member of the base. -/
theorem exists_maximal_containing_S :
    ∃ F : ConvexFilter L2, IsMaximal F ∧ ∀ n, S n ∈ F.carrier := by
  obtain ⟨G, hGsub, hGmax⟩ := exists_isMaximal_extension SBase
  refine ⟨G, hGmax, fun n => hGsub ?_⟩
  exact base_mem_ofAntitoneBase (isClosed_S n) (convex_S n)

variable {F : ConvexFilter L2}

/-- Every coordinate functional has a level hyperplane in such a filter, with support
value `1`.

The maximality hypothesis `hF` turns out to be unnecessary, and is kept per WO-06b
§1.12. -/
theorem coord_mem_Mset (hF : IsMaximal F) (h : ∀ n, S n ∈ F.carrier) (k : ℕ) :
    coordCLM k ∈ Mset F ∧ sig F (coordCLM k) = 1 := by
  have hsub : S k ⊆ hyperplane (coordCLM k) 1 := fun x hx => hx k le_rfl
  have hmem : hyperplane (coordCLM k) 1 ∈ F.carrier :=
    F.mem_of_superset (h k) (isClosed_hyperplane _ _) (convex_hyperplane _ _) hsub
  exact ⟨⟨1, hmem⟩, sig_eq_of_hyperplane_mem hmem⟩

/-- **Remark 8.7.** No point of `ℓ²` realizes the support number of such a filter: the
flat is empty. -/
theorem Aset_eq_empty (hF : IsMaximal F) (h : ∀ n, S n ∈ F.carrier) :
    {x : L2 | ∀ u ∈ Nset F, u x = sig F u} = ∅ := by
  rw [Set.eq_empty_iff_forall_notMem]
  intro x hx
  refine not_all_coords_one x fun k => ?_
  obtain ⟨hM, hsig⟩ := coord_mem_Mset hF h k
  have := hx (coordCLM k) (Mset_subset_Nset hF hM)
  rw [hsig] at this
  simpa using this

end RemarkInfinite

end ConvexFilter
