import ConvexFilters.Realization
import ConvexFilters.Annihilator
import ConvexFilters.SigCounterexample

/-!
# The generating family: what it does and does not force (Remarks 5.4, 8.2, 8.3)

## Part B — Remark 5.4, corrected

Remark 5.4 concerns the family of generators of Section 5. Two statements, one in each
direction, on `V = ℝ × ℝ`.

*The family can generate a maximal filter.* For `m = 1` the generators are the tail-rays
`ray k = {x | k ≤ x.1 ∧ x.2 = 0}` of a line, and the filter they generate is already
maximal: `generated_isMaximal_of_m_eq_one`. A convex set meeting every tail-ray meets the
line in a convex set with points of arbitrarily large first coordinate, hence contains a
tail-ray.

*The family need not generate a maximal filter.* For `(d,m) = (1,2)` the generators are the
hyperbola germs `hyp k` of `SigCounterexample.lean`, and the witness is the region under
the reciprocal logarithm. The filter generated by the germs is not maximal:
`generated_not_isMaximal`. This part discharges Remark 8.3 as well, whose example is the
same set.

**A correction to the work order.** WO-08 §4 gives the witness as

`logRegion = {p | 1 ≤ p.1 ∧ 1 / Real.log (p.1 + 2) ≤ p.2 ∧ p.2 ≤ 1}`,

a region in which the *first* coordinate is large and the second is small, and asks for
`(logRegion ∩ hyp k).Nonempty`. But `hyp k` of `SigCounterexample.lean` has the opposite
orientation: its points satisfy `p.1 ≤ 1 / (k+1)` and `p.2 ≥ k+1`, so they can meet
`{p | 1 ≤ p.1}` only when `k = 0`. The dispatched pair of statements is therefore
unsatisfiable as written, and `not_forall_logRegion_inter_hyp_nonempty` below records the
refutation. Both `logRegion` and its convexity and closedness are kept exactly as
dispatched; the comparison with `hyp` is made with the transposed region

`logRegionSwap = Prod.swap ⁻¹' logRegion = {p | 1 ≤ p.2 ∧ 1 / Real.log (p.2 + 2) ≤ p.1 ∧ p.1 ≤ 1}`,

which is the same set of the plane read in the orientation of `hyp`, and whose convexity
and closedness are transported from `logRegion`. All three statements of the remark
(`logRegionSwap_inter_hyp_nonempty`, `hyp_not_subset_logRegionSwap`,
`generated_not_isMaximal`) then hold.

Convexity of `logRegion` is the only real work. Rather than differentiating twice, we use
that `x ↦ Real.log (x + 2)` is concave and strictly positive on `[1, ∞)`, and that the
reciprocal of a positive concave function is convex (`convexOn_one_div_of_concaveOn`,
proved from the arithmetic–harmonic mean inequality); the region is then the epigraph of
that convex function intersected with a half-space.

## Part C — Remark 8.2

`eq_of_contains_gen`: two maximal convex filters both containing the whole family of
generators, for the same flag data `(b, a, d, m)` but with the growth rates unread, are
equal. No rate information distinguishes them.
-/

open Module

namespace ConvexFilter

namespace RemarkFamily

/-! ## Part B, first half — the tail-rays of a line generate a maximal filter -/

/-- The `k`-th tail-ray of the horizontal axis: the `m = 1` member of the generating
family, in the plane. -/
def ray (k : ℕ) : Set (ℝ × ℝ) := {x : ℝ × ℝ | (k : ℝ) ≤ x.1 ∧ x.2 = 0}

theorem ray_nonempty (k : ℕ) : (ray k).Nonempty := ⟨((k : ℝ), 0), le_rfl, rfl⟩

theorem ray_isClosed (k : ℕ) : IsClosed (ray k) := by
  have h1 : IsClosed {x : ℝ × ℝ | (k : ℝ) ≤ x.1} := isClosed_le continuous_const continuous_fst
  have h2 : IsClosed {x : ℝ × ℝ | x.2 = 0} := isClosed_eq continuous_snd continuous_const
  exact h1.inter h2

theorem ray_convex (k : ℕ) : Convex ℝ (ray k) := by
  rintro x ⟨hx1, hx2⟩ y ⟨hy1, hy2⟩ a b ha hb hab
  constructor
  · show (k : ℝ) ≤ a * x.1 + b * y.1
    nlinarith
  · show a * x.2 + b * y.2 = 0
    rw [hx2, hy2]; ring

theorem ray_antitone : Antitone ray := by
  intro m n hmn p hp
  exact ⟨le_trans (Nat.cast_le.mpr hmn) hp.1, hp.2⟩

/-- The convex filter generated by the tail-rays of the horizontal axis. -/
noncomputable def rayBase : ConvexFilter (ℝ × ℝ) :=
  ofAntitoneBase ray ray_nonempty ray_antitone

theorem mem_rayBase_iff {C : Set (ℝ × ℝ)} :
    C ∈ rayBase.carrier ↔ IsClosed C ∧ Convex ℝ C ∧ ∃ k, ray k ⊆ C := Iff.rfl

/-- **Remark 5.4, positive half.** For `m = 1` the generating family already generates a
maximal convex filter: the tail-rays of a line are a base of a maximal convex filter. -/
theorem generated_isMaximal_of_m_eq_one : IsMaximal rayBase := by
  rw [isMaximal_iff]
  intro C hCcl hCcv hCF
  -- no tail-ray is contained in `C`
  have hnosub : ∀ k : ℕ, ¬ ray k ⊆ C := by
    intro k hk
    exact hCF ⟨hCcl, hCcv, k, hk⟩
  -- the trace of `C` on the horizontal axis
  set S : Set ℝ := {t : ℝ | ((t : ℝ), (0 : ℝ)) ∈ C} with hSdef
  have hSconv : Convex ℝ S := by
    intro x hx y hy a b ha hb hab
    have : a • ((x : ℝ), (0 : ℝ)) + b • ((y : ℝ), (0 : ℝ)) = ((a * x + b * y : ℝ), (0 : ℝ)) := by
      simp
    have hmem := hCcv hx hy ha hb hab
    rwa [this] at hmem
  -- if every tail-ray met `C`, some tail-ray would be contained in `C`
  by_contra hcon
  push_neg at hcon
  have hmeet : ∀ k : ℕ, (ray k ∩ C).Nonempty := by
    intro k
    obtain ⟨p, hp⟩ := hcon (ray k) ⟨ray_isClosed k, ray_convex k, k, subset_rfl⟩
    exact ⟨p, hp.2, hp.1⟩
  have hunb : ∀ B : ℝ, ∃ s ∈ S, B ≤ s := by
    intro B
    obtain ⟨k, hk⟩ := exists_nat_ge B
    obtain ⟨p, ⟨hp1, hp2⟩, hpC⟩ := hmeet k
    refine ⟨p.1, ?_, le_trans hk hp1⟩
    have : ((p.1 : ℝ), (0 : ℝ)) = p := by
      rw [← hp2]
    rw [hSdef]
    simpa [this] using hpC
  obtain ⟨t₀, ht₀S, -⟩ := hunb 0
  obtain ⟨k₀, hk₀⟩ := exists_nat_ge t₀
  refine hnosub k₀ ?_
  rintro p ⟨hp1, hp2⟩
  obtain ⟨s, hsS, hs⟩ := hunb p.1
  have hmem : p.1 ∈ S :=
    hSconv.ordConnected.out ht₀S hsS ⟨le_trans hk₀ hp1, hs⟩
  have : ((p.1 : ℝ), (0 : ℝ)) = p := by rw [← hp2]
  rw [hSdef] at hmem
  simpa [this] using hmem

/-! ## Part B, second half — the reciprocal-logarithm region -/

/-- The arithmetic–harmonic mean inequality in the form needed for the reciprocal of a
concave function. -/
theorem one_div_convex_comb_le {A B lam mu : ℝ} (hA : 0 < A) (hB : 0 < B) (hlam : 0 ≤ lam)
    (hmu : 0 ≤ mu) (hsum : lam + mu = 1) :
    1 / (lam * A + mu * B) ≤ lam * (1 / A) + mu * (1 / B) := by
  have hden : 0 < lam * A + mu * B := by
    rcases (lt_or_eq_of_le hlam) with h | h
    · nlinarith
    · have : mu = 1 := by linarith
      nlinarith
  rw [div_le_iff₀ hden]
  have hkey : (lam * (1 / A) + mu * (1 / B)) * (lam * A + mu * B)
      = lam ^ 2 + mu ^ 2 + lam * mu * (A / B + B / A) := by
    field_simp
    ring
  rw [hkey]
  have hAB : 2 ≤ A / B + B / A := by
    rw [div_add_div _ _ (ne_of_gt hB) (ne_of_gt hA), le_div_iff₀ (by positivity)]
    nlinarith [sq_nonneg (A - B)]
  nlinarith [mul_nonneg hlam hmu]

/-- The reciprocal of a strictly positive concave function is convex. -/
theorem convexOn_one_div_of_concaveOn {s : Set ℝ} {f : ℝ → ℝ} (hf : ConcaveOn ℝ s f)
    (hpos : ∀ x ∈ s, 0 < f x) : ConvexOn ℝ s (fun x => 1 / f x) := by
  refine ⟨hf.1, fun x hx y hy a b ha hb hab => ?_⟩
  have hx' : 0 < f x := hpos x hx
  have hy' : 0 < f y := hpos y hy
  have hmem : a • x + b • y ∈ s := hf.1 hx hy ha hb hab
  have hconc : a • f x + b • f y ≤ f (a • x + b • y) := hf.2 hx hy ha hb hab
  have hposm : 0 < f (a • x + b • y) := hpos _ hmem
  have hlow : 0 < a * f x + b * f y := by
    rcases lt_or_eq_of_le ha with h | h
    · nlinarith
    · have hb1 : b = 1 := by linarith
      nlinarith
  have h1 : 1 / f (a • x + b • y) ≤ 1 / (a * f x + b * f y) := by
    apply one_div_le_one_div_of_le hlow
    simpa using hconc
  have h2 : 1 / (a * f x + b * f y) ≤ a * (1 / f x) + b * (1 / f y) :=
    one_div_convex_comb_le hx' hy' ha hb hab
  simpa using le_trans h1 h2

theorem log_add_two_pos {x : ℝ} (hx : 1 ≤ x) : 0 < Real.log (x + 2) :=
  Real.log_pos (by linarith)

/-- `x ↦ Real.log (x + 2)` is concave on `[1, ∞)`. -/
theorem concaveOn_log_add_two : ConcaveOn ℝ (Set.Ici (1 : ℝ)) (fun x => Real.log (x + 2)) := by
  refine ⟨convex_Ici 1, fun x hx y hy a b ha hb hab => ?_⟩
  have hx0 : (0 : ℝ) < x + 2 := by
    have : (1 : ℝ) ≤ x := hx
    linarith
  have hy0 : (0 : ℝ) < y + 2 := by
    have : (1 : ℝ) ≤ y := hy
    linarith
  have hcomb := (strictConcaveOn_log_Ioi.concaveOn).2 (Set.mem_Ioi.2 hx0) (Set.mem_Ioi.2 hy0)
    ha hb hab
  have hrw : a • (x + 2) + b • (y + 2) = (a • x + b • y) + 2 := by
    simp only [smul_eq_mul]
    nlinarith [hab]
  rwa [hrw] at hcomb

/-- `x ↦ 1 / Real.log (x + 2)` is convex on `[1, ∞)`. -/
theorem convexOn_one_div_log_add_two :
    ConvexOn ℝ (Set.Ici (1 : ℝ)) (fun x => 1 / Real.log (x + 2)) :=
  convexOn_one_div_of_concaveOn concaveOn_log_add_two fun _ hx => log_add_two_pos hx

/-- The region under the reciprocal logarithm: a closed convex set meeting every generator
of the `(d,m) = (1,2)` family without containing any of them. -/
def logRegion : Set (ℝ × ℝ) :=
  {p : ℝ × ℝ | 1 ≤ p.1 ∧ 1 / Real.log (p.1 + 2) ≤ p.2 ∧ p.2 ≤ 1}

theorem convex_logRegion : Convex ℝ logRegion := by
  have h1 : Convex ℝ {p : ℝ × ℝ | p.1 ∈ Set.Ici (1 : ℝ) ∧ 1 / Real.log (p.1 + 2) ≤ p.2} :=
    convexOn_one_div_log_add_two.convex_epigraph
  have h2 : Convex ℝ {p : ℝ × ℝ | p.2 ≤ 1} := by
    intro x hx y hy a b ha hb hab
    show a * x.2 + b * y.2 ≤ 1
    have hx' : x.2 ≤ 1 := hx
    have hy' : y.2 ≤ 1 := hy
    nlinarith
  have hEq : logRegion =
      {p : ℝ × ℝ | p.1 ∈ Set.Ici (1 : ℝ) ∧ 1 / Real.log (p.1 + 2) ≤ p.2} ∩
        {p : ℝ × ℝ | p.2 ≤ 1} := by
    ext p
    simp only [logRegion, Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_Ici, and_assoc]
  rw [hEq]
  exact h1.inter h2

theorem continuous_one_div_log_max :
    Continuous fun x : ℝ => 1 / Real.log (max x 1 + 2) := by
  have hmax : Continuous fun x : ℝ => max x 1 + 2 :=
    (continuous_id.max continuous_const).add continuous_const
  have hne : ∀ x : ℝ, max x 1 + 2 ∈ ({0} : Set ℝ)ᶜ := by
    intro x
    have : (1 : ℝ) ≤ max x 1 := le_max_right _ _
    simp only [Set.mem_compl_iff, Set.mem_singleton_iff]
    intro h
    linarith
  have hlog : Continuous fun x : ℝ => Real.log (max x 1 + 2) :=
    Real.continuousOn_log.comp_continuous hmax hne
  refine continuous_const.div hlog fun x => ?_
  have : (1 : ℝ) ≤ max x 1 := le_max_right _ _
  exact ne_of_gt (Real.log_pos (by linarith))

theorem isClosed_logRegion : IsClosed logRegion := by
  have h1 : IsClosed {p : ℝ × ℝ | 1 ≤ p.1} := isClosed_le continuous_const continuous_fst
  have h2 : IsClosed {p : ℝ × ℝ | 1 / Real.log (max p.1 1 + 2) ≤ p.2} :=
    isClosed_le (continuous_one_div_log_max.comp continuous_fst) continuous_snd
  have h3 : IsClosed {p : ℝ × ℝ | p.2 ≤ 1} := isClosed_le continuous_snd continuous_const
  have hEq : logRegion = ({p : ℝ × ℝ | 1 ≤ p.1} ∩
      {p : ℝ × ℝ | 1 / Real.log (max p.1 1 + 2) ≤ p.2}) ∩ {p : ℝ × ℝ | p.2 ≤ 1} := by
    ext p
    simp only [logRegion, Set.mem_inter_iff, Set.mem_setOf_eq, and_assoc]
    constructor
    · rintro ⟨ha, hb, hc⟩
      exact ⟨ha, by rwa [max_eq_left ha], hc⟩
    · rintro ⟨ha, hb, hc⟩
      exact ⟨ha, by rwa [max_eq_left ha] at hb, hc⟩
  rw [hEq]
  exact (h1.inter h2).inter h3

/-! ### The transposed region, in the orientation of the hyperbola germs -/

/-- The swap of the plane, as a continuous linear map. -/
noncomputable def swapCLM : (ℝ × ℝ) →L[ℝ] (ℝ × ℝ) :=
  (ContinuousLinearMap.snd ℝ ℝ ℝ).prod (ContinuousLinearMap.fst ℝ ℝ ℝ)

@[simp] theorem swapCLM_apply (p : ℝ × ℝ) : swapCLM p = (p.2, p.1) := rfl

/-- `logRegion` read in the orientation of the hyperbola germs `hyp`: the first coordinate
is the small one. -/
def logRegionSwap : Set (ℝ × ℝ) :=
  {p : ℝ × ℝ | 1 ≤ p.2 ∧ 1 / Real.log (p.2 + 2) ≤ p.1 ∧ p.1 ≤ 1}

theorem logRegionSwap_eq_preimage : logRegionSwap = swapCLM ⁻¹' logRegion := by
  ext p
  simp only [logRegionSwap, logRegion, Set.mem_preimage, Set.mem_setOf_eq, swapCLM_apply]

theorem convex_logRegionSwap : Convex ℝ logRegionSwap := by
  rw [logRegionSwap_eq_preimage]
  exact convex_logRegion.linear_preimage (swapCLM : (ℝ × ℝ) →ₗ[ℝ] (ℝ × ℝ))

theorem isClosed_logRegionSwap : IsClosed logRegionSwap := by
  rw [logRegionSwap_eq_preimage]
  exact isClosed_logRegion.preimage swapCLM.continuous

open SigCounterexample in
/-- Every hyperbola germ meets the transposed region. -/
theorem logRegionSwap_inter_hyp_nonempty (k : ℕ) :
    (logRegionSwap ∩ hyp k).Nonempty := by
  have hk1 : (0 : ℝ) < (k : ℝ) + 1 := by positivity
  set y : ℝ := Real.exp ((k : ℝ) + 1) with hy
  have hylarge : (k : ℝ) + 1 ≤ y := by
    have := Real.add_one_le_exp ((k : ℝ) + 1)
    rw [← hy] at this
    linarith
  have hy1 : (1 : ℝ) ≤ y := by linarith
  have hlog : (k : ℝ) + 1 ≤ Real.log (y + 2) := by
    have hmono : Real.log y ≤ Real.log (y + 2) :=
      Real.log_le_log (by linarith) (by linarith)
    rw [hy, Real.log_exp] at hmono
    exact hmono
  have hlogpos : 0 < Real.log (y + 2) := lt_of_lt_of_le hk1 hlog
  refine ⟨(1 / ((k : ℝ) + 1), y), ⟨hy1, ?_, ?_⟩, ?_, ?_, ?_, ?_⟩
  · show 1 / Real.log (y + 2) ≤ 1 / ((k : ℝ) + 1)
    exact one_div_le_one_div_of_le hk1 hlog
  · show 1 / ((k : ℝ) + 1) ≤ 1
    rw [div_le_one hk1]
    have : (0 : ℝ) ≤ (k : ℝ) := Nat.cast_nonneg k
    linarith
  · show (0 : ℝ) ≤ 1 / ((k : ℝ) + 1)
    positivity
  · show (0 : ℝ) ≤ y
    linarith
  · show (1 : ℝ) ≤ 1 / ((k : ℝ) + 1) * y
    rw [div_mul_eq_mul_div, one_mul, le_div_iff₀ hk1]
    linarith
  · show 1 / ((k : ℝ) + 1) * ((k : ℝ) + 1) ≤ 1
    rw [div_mul_cancel₀ _ (ne_of_gt hk1)]

open SigCounterexample in
/-- No hyperbola germ is contained in the transposed region: the germ decays like `1/x`,
which is eventually below `1 / log (x + 2)`. -/
theorem hyp_not_subset_logRegionSwap (k : ℕ) : ¬ hyp k ⊆ logRegionSwap := by
  intro hsub
  have hk0 : (0 : ℝ) ≤ (k : ℝ) := Nat.cast_nonneg k
  set N : ℝ := (k : ℝ) + 3 with hN
  set y : ℝ := Real.exp N - 2 with hy
  -- `exp (k+3) = exp (k+1) * exp 2 ≥ (k+2) * 3`
  have hexp2 : (3 : ℝ) ≤ Real.exp 2 := by
    have := Real.add_one_le_exp (2 : ℝ)
    linarith
  have hexp1 : (k : ℝ) + 2 ≤ Real.exp ((k : ℝ) + 1) := by
    have := Real.add_one_le_exp ((k : ℝ) + 1)
    linarith
  have hpos1 : (0 : ℝ) < Real.exp ((k : ℝ) + 1) := Real.exp_pos _
  have hsplit : Real.exp N = Real.exp ((k : ℝ) + 1) * Real.exp 2 := by
    rw [← Real.exp_add, hN]
    ring_nf
  have hbig : 3 * ((k : ℝ) + 2) ≤ Real.exp N := by
    rw [hsplit]
    nlinarith
  have hylarge : (k : ℝ) + 4 ≤ y := by
    rw [hy]
    nlinarith
  have hypos : (0 : ℝ) < y := by linarith
  have hlogy : Real.log (y + 2) = N := by
    rw [hy]
    simp only [sub_add_cancel]
    exact Real.log_exp N
  have hmem : ((1 / y : ℝ), y) ∈ hyp k := by
    refine ⟨by positivity, le_of_lt hypos, ?_, ?_⟩
    · show (1 : ℝ) ≤ 1 / y * y
      rw [div_mul_cancel₀ _ (ne_of_gt hypos)]
    · show 1 / y * ((k : ℝ) + 1) ≤ 1
      rw [div_mul_eq_mul_div, one_mul, div_le_one hypos]
      linarith
  have hmem' := hsub hmem
  have hineq : 1 / Real.log (y + 2) ≤ 1 / y := hmem'.2.1
  rw [hlogy] at hineq
  have hNpos : (0 : ℝ) < N := by rw [hN]; linarith
  have : y ≤ N := le_of_one_div_le_one_div hNpos hineq
  rw [hN] at this
  linarith

/-- **Remark 5.4, negative half, and Remark 8.3.** For `(d,m) = (1,2)` the family of
generators does not generate a maximal convex filter: the region under the reciprocal
logarithm meets every generator without containing any of them, so it can be adjoined. -/
theorem generated_not_isMaximal : ¬ IsMaximal SigCounterexample.hypBase := by
  intro hmax
  have hnot : logRegionSwap ∉ SigCounterexample.hypBase.carrier := by
    rintro ⟨-, -, k, hk⟩
    exact hyp_not_subset_logRegionSwap k hk
  obtain ⟨D, hD, hdisj⟩ :=
    (isMaximal_iff _).1 hmax isClosed_logRegionSwap convex_logRegionSwap hnot
  obtain ⟨-, -, k, hk⟩ := hD
  obtain ⟨p, hp1, hp2⟩ := logRegionSwap_inter_hyp_nonempty k
  have : p ∈ logRegionSwap ∩ D := ⟨hp1, hk hp2⟩
  rw [hdisj] at this
  exact this

open SigCounterexample in
/-- The statement of WO-08 §4 in its literal form is false: the region `logRegion` is
disjoint from the hyperbola germ `hyp 1`, because the two are written in opposite
orientations. The corrected pair of statements is
`logRegionSwap_inter_hyp_nonempty` / `hyp_not_subset_logRegionSwap`. -/
theorem not_forall_logRegion_inter_hyp_nonempty :
    ¬ ∀ k : ℕ, (logRegion ∩ hyp k).Nonempty := by
  intro h
  obtain ⟨p, hp1, hp2⟩ := h 1
  have hfst : (1 : ℝ) ≤ p.1 := hp1.1
  have hle : p.1 * ((1 : ℕ) + 1 : ℝ) ≤ 1 := hp2.2.2.2
  norm_num at hle
  linarith

end RemarkFamily

/-! ## Part C — Remark 8.2: no rate information is visible to the filter -/

section PartC

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V] [FiniteDimensional ℝ V]

omit [FiniteDimensional ℝ V] in
theorem eq_of_carrier_eq {F F' : ConvexFilter V} (h : F.carrier = F'.carrier) : F = F' := by
  obtain ⟨c, h1, h2, h3, h4, h5, h6⟩ := F
  obtain ⟨c', h1', h2', h3', h4', h5', h6'⟩ := F'
  simp only at h
  subst h
  rfl

/-- **Remark 8.2.** Two maximal convex filters containing the whole generating family for
the same flag data `(b, a, d, m)` are equal: the growth rates `K`, `M`, `c` of the
generators carry no information the filter can see. -/
theorem eq_of_contains_gen {F F' : ConvexFilter V} (hF : IsMaximal F) (hF' : IsMaximal F')
    {n : ℕ} (b : Basis (Fin n) ℝ V) (a : V) {d m : ℕ}
    (hd : 1 ≤ d) (hdm : d ≤ m) (hmn : m ≤ n)
    (h : ∀ k : ℕ, gen b a d m ((k : ℝ) + 1) ((k : ℝ) + 1) (1 / ((k : ℝ) + 1)) ∈ F.carrier)
    (h' : ∀ k : ℕ, gen b a d m ((k : ℝ) + 1) ((k : ℝ) + 1) (1 / ((k : ℝ) + 1)) ∈ F'.carrier) :
    F = F' := by
  have hgen : ∀ k : ℕ, 1 ≤ k →
      gen b a d m (k : ℝ) (k : ℝ) (1 / (k : ℝ)) ∈ F.carrier := by
    rintro (_ | j) hk
    · exact absurd hk (by omega)
    · have := h j
      push_cast
      exact this
  have hgen' : ∀ k : ℕ, 1 ≤ k →
      gen b a d m (k : ℝ) (k : ℝ) (1 / (k : ℝ)) ∈ F'.carrier := by
    rintro (_ | j) hk
    · exact absurd hk (by omega)
    · have := h' j
      push_cast
      exact this
  have hA : Aset F = Aset F' := by
    rw [forcing_Aset hF hd hdm hmn hgen, forcing_Aset hF' hd hdm hmn hgen']
  have hQ : Qset F = Qset F' := by
    rw [forcing_Qset hF hd hdm hmn hgen, forcing_Qset hF' hd hdm hmn hgen']
  exact eq_of_carrier_eq (carrier_eq_of_Aset_Qset hF hF' hA hQ)

end PartC

end ConvexFilter
