import ConvexFilters.Principal
import ConvexFilters.SigCounterexample

/-!
# The space of maximal convex filters: the covering criterion (Section 9, Parts A and B)

This file is the combinatorial core of Section 9 of the paper, stated with no reference to
the topology on the set of maximal convex filters.

## Part A — the covering criterion

* `exists_mem_of_cover` (Lemma 9.1): a maximal convex filter contains a member of every
  finite cover of the ambient space by closed convex sets;
* `cover_of_forall_mem` (Lemma 9.1, converse): a finite family of sets meeting every
  maximal convex filter covers the space;
* `Separated`: the combinatorial separation relation, a finite closed convex cover no
  member of which lies in both filters;
* `Separated.symm`, `not_separated_self`.

## Part B — the three filters over a line

In `V = ℝ × ℝ`, with `ℓ = {p | p.1 = 0}`:

* `Fline`, the filter generated by the upward tail-rays `upRay k` of `ℓ`, maximal by
  `Fline_isMaximal`, with membership criterion `mem_Fline_iff`;
* `SigCounterexample.Ghyp`, from `ConvexFilters/SigCounterexample.lean`, confined to `ℓ`
  from the right;
* `Fminus`, its reflection in the `y`-axis, maximal by `Fminus_isMaximal`.

`comapEquiv` transports a convex filter along a continuous linear automorphism, and
`comapEquiv_isMaximal` transports maximality; `Fminus` is obtained this way.

The geometric input of Part C is `wedge` (Lemma 9.3): a closed convex set containing an
upward tail-ray of `ℓ` and one point with positive first coordinate belongs to `Ghyp`.
-/

namespace ConvexFilter

namespace Space

/-! ## Part A — the covering criterion -/

section PartA

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V] [FiniteDimensional ℝ V]

open Classical in
/-- A member of `F` disjoint from `E`, when one exists, and `Set.univ` otherwise. -/
noncomputable def avoid (F : ConvexFilter V) (E : Set V) : Set V :=
  if h : ∃ D ∈ F.carrier, E ∩ D = ∅ then h.choose else Set.univ

omit [FiniteDimensional ℝ V] in
theorem avoid_mem (F : ConvexFilter V) (E : Set V) : avoid F E ∈ F.carrier := by
  classical
  unfold avoid
  split
  · rename_i h
    exact h.choose_spec.1
  · exact F.univ_mem

omit [FiniteDimensional ℝ V] in
theorem inter_avoid_eq_empty {F : ConvexFilter V} {E : Set V}
    (h : ∃ D ∈ F.carrier, E ∩ D = ∅) : E ∩ avoid F E = ∅ := by
  classical
  unfold avoid
  rw [dif_pos h]
  exact h.choose_spec.2

omit [FiniteDimensional ℝ V] in
theorem iInter_avoid_mem (F : ConvexFilter V) (s : Finset (Set V)) :
    (⋂ E ∈ s, avoid F E) ∈ F.carrier := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using F.univ_mem
  | insert a t _ha ih =>
      rw [Finset.set_biInter_insert]
      exact F.inter_mem (avoid_mem F a) ih

/-- **Lemma 9.1.** A maximal convex filter contains a member of every finite cover of the
ambient space by closed convex sets. -/
theorem exists_mem_of_cover {s : Finset (Set V)}
    (hcl : ∀ E ∈ s, IsClosed E) (hcv : ∀ E ∈ s, Convex ℝ E)
    (hcover : (⋃ E ∈ s, E) = Set.univ)
    {F : ConvexFilter V} (hF : IsMaximal F) :
    ∃ E ∈ s, E ∈ F.carrier := by
  classical
  by_contra hcon
  push_neg at hcon
  have havoid : ∀ E ∈ s, E ∩ avoid F E = ∅ := by
    intro E hE
    exact inter_avoid_eq_empty ((isMaximal_iff F).mp hF (hcl E hE) (hcv E hE) (hcon E hE))
  obtain ⟨x, hx⟩ := nonempty_of_mem (iInter_avoid_mem F s)
  have hxuniv : x ∈ (⋃ E ∈ s, E) := by rw [hcover]; exact Set.mem_univ x
  simp only [Set.mem_iUnion] at hxuniv
  obtain ⟨E, hEs, hxE⟩ := hxuniv
  have hxa : x ∈ avoid F E := by
    simp only [Set.mem_iInter] at hx
    exact hx E hEs
  have : x ∈ E ∩ avoid F E := ⟨hxE, hxa⟩
  rw [havoid E hEs] at this
  exact this

/-- **Lemma 9.1, converse.** A finite family of sets meeting every maximal convex filter
covers the space; the principal filters suffice. -/
theorem cover_of_forall_mem {s : Finset (Set V)}
    (h : ∀ (F : ConvexFilter V), IsMaximal F → ∃ E ∈ s, E ∈ F.carrier) :
    (⋃ E ∈ s, E) = Set.univ := by
  refine Set.eq_univ_of_forall fun p => ?_
  obtain ⟨E, hEs, hE⟩ := h (principal p) (principal_isMaximal p)
  rw [mem_principal_iff] at hE
  exact Set.mem_biUnion hEs hE.2.2

/-- Two convex filters are *separated* when some finite cover of the space by closed convex
sets has no member belonging to both. -/
def Separated (F F' : ConvexFilter V) : Prop :=
  ∃ s : Finset (Set V), (∀ E ∈ s, IsClosed E) ∧ (∀ E ∈ s, Convex ℝ E) ∧
    (⋃ E ∈ s, E) = Set.univ ∧ ∀ E ∈ s, ¬(E ∈ F.carrier ∧ E ∈ F'.carrier)

theorem Separated.symm {F F' : ConvexFilter V} : Separated F F' → Separated F' F := by
  rintro ⟨s, hcl, hcv, hcover, hsep⟩
  exact ⟨s, hcl, hcv, hcover, fun E hE hmem => hsep E hE ⟨hmem.2, hmem.1⟩⟩

/-- A maximal convex filter is not separated from itself. -/
theorem not_separated_self (F : ConvexFilter V) (hF : IsMaximal F) : ¬ Separated F F := by
  rintro ⟨s, hcl, hcv, hcover, hsep⟩
  obtain ⟨E, hEs, hE⟩ := exists_mem_of_cover hcl hcv hcover hF
  exact hsep E hEs ⟨hE, hE⟩

/-! ### Transport of convex filters along a linear automorphism -/

/-- The convex filter of sets whose preimage under a continuous linear automorphism `e`
belongs to `F`. -/
def comapEquiv (e : V ≃L[ℝ] V) (F : ConvexFilter V) : ConvexFilter V where
  carrier := {C : Set V | (⇑e ⁻¹' C) ∈ F.carrier}
  isClosed_of_mem := by
    intro C hC
    have h : (⇑e.symm ⁻¹' (⇑e ⁻¹' C)) = C := by
      ext x; simp
    rw [← h]
    exact (F.isClosed_of_mem hC).preimage e.symm.continuous
  convex_of_mem := by
    intro C hC
    have h : (⇑e.symm ⁻¹' (⇑e ⁻¹' C)) = C := by
      ext x; simp
    rw [← h]
    exact (F.convex_of_mem hC).linear_preimage (e.symm : V →ₗ[ℝ] V)
  univ_mem := by simpa using F.univ_mem
  empty_not_mem := by simpa using F.empty_not_mem
  inter_mem := by
    intro C D hC hD
    rw [Set.mem_setOf_eq, Set.preimage_inter]
    exact F.inter_mem hC hD
  mem_of_superset := by
    intro C D hC hDcl hDcv hCD
    refine F.mem_of_superset hC (hDcl.preimage e.continuous)
      (hDcv.linear_preimage (e : V →ₗ[ℝ] V)) ?_
    exact Set.preimage_mono hCD

omit [FiniteDimensional ℝ V] in
theorem mem_comapEquiv_iff {e : V ≃L[ℝ] V} {F : ConvexFilter V} {C : Set V} :
    C ∈ (comapEquiv e F).carrier ↔ (⇑e ⁻¹' C) ∈ F.carrier := Iff.rfl

omit [FiniteDimensional ℝ V] in
theorem comapEquiv_isMaximal (e : V ≃L[ℝ] V) {F : ConvexFilter V} (hF : IsMaximal F) :
    IsMaximal (comapEquiv e F) := by
  rw [isMaximal_iff]
  intro C hCcl hCcv hC
  rw [mem_comapEquiv_iff] at hC
  obtain ⟨D, hD, hdisj⟩ := (isMaximal_iff F).mp hF (hCcl.preimage e.continuous)
    (hCcv.linear_preimage (e : V →ₗ[ℝ] V)) hC
  refine ⟨⇑e.symm ⁻¹' D, ?_, ?_⟩
  · show (⇑e ⁻¹' (⇑e.symm ⁻¹' D)) ∈ F.carrier
    have h : (⇑e ⁻¹' (⇑e.symm ⁻¹' D)) = D := by ext x; simp
    rwa [h]
  · ext x
    simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_empty_iff_false, iff_false, not_and]
    intro hxC hxD
    have : e.symm x ∈ (⇑e ⁻¹' C) ∩ D := by
      refine ⟨?_, hxD⟩
      simpa using hxC
    rw [hdisj] at this
    exact this

omit [FiniteDimensional ℝ V] in
/-- `Separated` transports along a continuous linear automorphism. -/
theorem Separated.comapEquiv {F F' : ConvexFilter V} (e : V ≃L[ℝ] V) (h : Separated F F') :
    Separated (Space.comapEquiv e F) (Space.comapEquiv e F') := by
  classical
  obtain ⟨s, hcl, hcv, hcover, hsep⟩ := h
  refine ⟨s.image (fun E => ⇑e.symm ⁻¹' E), ?_, ?_, ?_, ?_⟩
  · intro E hE
    obtain ⟨E', hE', rfl⟩ := Finset.mem_image.mp hE
    exact (hcl E' hE').preimage e.symm.continuous
  · intro E hE
    obtain ⟨E', hE', rfl⟩ := Finset.mem_image.mp hE
    exact (hcv E' hE').linear_preimage (e.symm : V →ₗ[ℝ] V)
  · refine Set.eq_univ_of_forall fun p => ?_
    have : e.symm p ∈ (⋃ E ∈ s, E) := by rw [hcover]; exact Set.mem_univ _
    simp only [Set.mem_iUnion] at this
    obtain ⟨E, hEs, hpE⟩ := this
    refine Set.mem_biUnion (Finset.mem_image_of_mem (fun E => ⇑e.symm ⁻¹' E) hEs) ?_
    exact hpE
  · intro E hE
    obtain ⟨E', hE', rfl⟩ := Finset.mem_image.mp hE
    have hpre : (⇑e ⁻¹' (⇑e.symm ⁻¹' E')) = E' := by ext x; simp
    rintro ⟨h1, h2⟩
    rw [mem_comapEquiv_iff, hpre] at h1 h2
    exact hsep E' hE' ⟨h1, h2⟩

end PartA

/-! ## Part B — the three filters over a line -/

section PartB

open SigCounterexample

/-- The `k`-th upward tail-ray of the vertical axis `ℓ = {p | p.1 = 0}`. -/
def upRay (k : ℕ) : Set (ℝ × ℝ) := {p : ℝ × ℝ | (k : ℝ) ≤ p.2 ∧ p.1 = 0}

theorem upRay_nonempty (k : ℕ) : (upRay k).Nonempty := ⟨(0, (k : ℝ)), le_rfl, rfl⟩

theorem upRay_isClosed (k : ℕ) : IsClosed (upRay k) := by
  have h1 : IsClosed {p : ℝ × ℝ | (k : ℝ) ≤ p.2} := isClosed_le continuous_const continuous_snd
  have h2 : IsClosed {p : ℝ × ℝ | p.1 = 0} := isClosed_eq continuous_fst continuous_const
  exact h1.inter h2

theorem upRay_convex (k : ℕ) : Convex ℝ (upRay k) := by
  rintro x ⟨hx1, hx2⟩ y ⟨hy1, hy2⟩ a b ha hb hab
  constructor
  · show (k : ℝ) ≤ a * x.2 + b * y.2
    nlinarith
  · show a * x.1 + b * y.1 = 0
    rw [hx2, hy2]; ring

theorem upRay_antitone : Antitone upRay := by
  intro m n hmn p hp
  exact ⟨le_trans (Nat.cast_le.mpr hmn) hp.1, hp.2⟩

/-- The convex filter generated by the upward tail-rays of the vertical axis. -/
noncomputable def Fline : ConvexFilter (ℝ × ℝ) :=
  ofAntitoneBase upRay upRay_nonempty upRay_antitone

theorem mem_Fline_iff {C : Set (ℝ × ℝ)} (hcl : IsClosed C) (hcv : Convex ℝ C) :
    C ∈ Fline.carrier ↔ ∃ k : ℕ, upRay k ⊆ C := by
  constructor
  · rintro ⟨-, -, k, hk⟩
    exact ⟨k, hk⟩
  · rintro ⟨k, hk⟩
    exact ⟨hcl, hcv, k, hk⟩

/-- A closed convex set whose trace on the vertical axis is unbounded above contains an
upward tail-ray. -/
theorem exists_upRay_subset {C : Set (ℝ × ℝ)} (hcv : Convex ℝ C)
    (hunb : ∀ B : ℝ, ∃ y : ℝ, B ≤ y ∧ ((0 : ℝ), y) ∈ C) :
    ∃ k : ℕ, upRay k ⊆ C := by
  set S : Set ℝ := {t : ℝ | ((0 : ℝ), t) ∈ C} with hSdef
  have hSconv : Convex ℝ S := by
    intro x hx y hy a b ha hb hab
    have hcomb : a • ((0 : ℝ), (x : ℝ)) + b • ((0 : ℝ), (y : ℝ)) = ((0 : ℝ), (a * x + b * y : ℝ)) := by
      simp
    have hmem := hcv hx hy ha hb hab
    rwa [hcomb] at hmem
  obtain ⟨t₀, ht₀, ht₀C⟩ := hunb 0
  obtain ⟨k₀, hk₀⟩ := exists_nat_ge t₀
  refine ⟨k₀, ?_⟩
  rintro p ⟨hp1, hp2⟩
  obtain ⟨y, hy, hyC⟩ := hunb p.2
  have hmem : p.2 ∈ S :=
    hSconv.ordConnected.out (ht₀C : t₀ ∈ S) (hyC : y ∈ S) ⟨le_trans hk₀ hp1, hy⟩
  have hpeq : ((0 : ℝ), p.2) = p := by
    rw [← hp2]
  rw [hSdef] at hmem
  simpa [hpeq] using hmem

/-- **The line filter is maximal.** The argument is that of
`RemarkFamily.generated_isMaximal_of_m_eq_one`, in the vertical orientation: a closed
convex set meeting every upward tail-ray meets the axis in an order-connected set that is
unbounded above, hence contains a tail-ray. -/
theorem Fline_isMaximal : IsMaximal Fline := by
  rw [isMaximal_iff]
  intro C hCcl hCcv hCF
  have hnosub : ∀ k : ℕ, ¬ upRay k ⊆ C := fun k hk => hCF ⟨hCcl, hCcv, k, hk⟩
  by_contra hcon
  push_neg at hcon
  have hmeet : ∀ k : ℕ, (upRay k ∩ C).Nonempty := by
    intro k
    obtain ⟨p, hp⟩ := hcon (upRay k) ⟨upRay_isClosed k, upRay_convex k, k, subset_rfl⟩
    exact ⟨p, hp.2, hp.1⟩
  have hunb : ∀ B : ℝ, ∃ y : ℝ, B ≤ y ∧ ((0 : ℝ), y) ∈ C := by
    intro B
    obtain ⟨k, hk⟩ := exists_nat_ge B
    obtain ⟨p, ⟨hp1, hp2⟩, hpC⟩ := hmeet k
    refine ⟨p.2, le_trans hk hp1, ?_⟩
    have hpeq : ((0 : ℝ), p.2) = p := by rw [← hp2]
    rw [hpeq]
    exact hpC
  obtain ⟨k, hk⟩ := exists_upRay_subset hCcv hunb
  exact hnosub k hk

/-! ### The reflected filter -/

/-- The reflection of the plane in the `y`-axis, as a continuous linear automorphism. -/
noncomputable def reflCLM : (ℝ × ℝ) ≃L[ℝ] (ℝ × ℝ) :=
  { toFun := fun p => (-p.1, p.2)
    invFun := fun p => (-p.1, p.2)
    map_add' := by intro p q; simp [Prod.ext_iff]; ring
    map_smul' := by intro c p; simp
    left_inv := by intro p; simp
    right_inv := by intro p; simp
    continuous_toFun := by
      exact (continuous_fst.neg.prodMk continuous_snd)
    continuous_invFun := by
      exact (continuous_fst.neg.prodMk continuous_snd) }

@[simp] theorem reflCLM_apply (p : ℝ × ℝ) : reflCLM p = (-p.1, p.2) := rfl

/-- The reflection of `Ghyp` in the `y`-axis: the filter confined to the vertical axis from
the left, with upward escape. -/
noncomputable def Fminus : ConvexFilter (ℝ × ℝ) := comapEquiv reflCLM Ghyp

theorem Fminus_isMaximal : IsMaximal Fminus := comapEquiv_isMaximal reflCLM Ghyp_isMaximal

theorem mem_Fminus_iff {C : Set (ℝ × ℝ)} :
    C ∈ Fminus.carrier ↔ (⇑reflCLM ⁻¹' C) ∈ Ghyp.carrier := Iff.rfl

/-! ### Lemma 9.3, the wedge -/

/-- **Lemma 9.3.** A closed convex set containing an upward tail-ray of the vertical axis
together with a point of positive first coordinate belongs to `Ghyp`: the convex hull of
the ray and the point contains a hyperbola germ. -/
theorem wedge {E : Set (ℝ × ℝ)} (hcl : IsClosed E) (hcv : Convex ℝ E)
    {a : ℝ} (hray : {p : ℝ × ℝ | a ≤ p.2 ∧ p.1 = 0} ⊆ E)
    {x₀ y₀ : ℝ} (hx₀ : 0 < x₀) (hmem : (x₀, y₀) ∈ E) :
    E ∈ SigCounterexample.Ghyp.carrier := by
  obtain ⟨k, hk⟩ := exists_nat_ge (max (2 / x₀) (|a| + |y₀|))
  have hk1 : 2 / x₀ ≤ (k : ℝ) := le_trans (le_max_left _ _) hk
  have hk2 : |a| + |y₀| ≤ (k : ℝ) := le_trans (le_max_right _ _) hk
  refine mem_carrier_of_base_subset hyp_mem_Ghyp hcl hcv (n := k) ?_
  intro p hp
  have hp1 : 0 < p.1 := hyp_pos hp
  have hpsnd : (k : ℝ) + 1 ≤ p.2 := hyp_snd_ge hp
  have hple : p.1 * ((k : ℝ) + 1) ≤ 1 := hp.2.2.2
  -- `p.1 ≤ x₀ / 2`
  have hkpos : (0 : ℝ) < (k : ℝ) + 1 := by positivity
  have hx0k : 2 / x₀ ≤ (k : ℝ) + 1 := by linarith
  have h2x : 2 ≤ x₀ * ((k : ℝ) + 1) := by
    rw [div_le_iff₀ hx₀] at hk1
    nlinarith
  have hpx : p.1 ≤ x₀ / 2 := by nlinarith
  set t : ℝ := p.1 / x₀ with ht
  have ht0 : 0 < t := by positivity
  have ht2 : t ≤ 1 / 2 := by
    rw [ht, div_le_div_iff₀ hx₀ (by norm_num)]
    linarith
  have ht1 : t < 1 := by linarith
  have hden : (0 : ℝ) < 1 - t := by linarith
  set y : ℝ := (p.2 - t * y₀) / (1 - t) with hy
  have hy₀abs : y₀ ≤ |y₀| := le_abs_self y₀
  have hy₀abs' : -|y₀| ≤ y₀ := neg_abs_le y₀
  have haabs : a ≤ |a| := le_abs_self a
  have habs0 : (0 : ℝ) ≤ |y₀| := abs_nonneg y₀
  have hnum : |a| + 1 ≤ p.2 - t * y₀ := by nlinarith
  have hya : a ≤ y := by
    rw [hy, le_div_iff₀ hden]
    nlinarith
  have hraymem : ((0 : ℝ), y) ∈ E := hray ⟨hya, rfl⟩
  have hcomb := hcv hmem hraymem (le_of_lt ht0) (le_of_lt hden) (by ring)
  have hfst : t * x₀ + (1 - t) * 0 = p.1 := by
    rw [ht]
    field_simp
    ring
  have hsnd : t * y₀ + (1 - t) * y = p.2 := by
    rw [hy]
    field_simp
    ring
  have hpeq : t • ((x₀ : ℝ), y₀) + (1 - t) • ((0 : ℝ), y) = p := by
    have : t • ((x₀ : ℝ), y₀) + (1 - t) • ((0 : ℝ), y)
        = (t * x₀ + (1 - t) * 0, t * y₀ + (1 - t) * y) := by
      simp
    rw [this, hfst, hsnd]
  rwa [hpeq] at hcomb

end PartB

end Space

end ConvexFilter
