import ConvexFilters.SpaceSep

/-!
# The space of maximal convex filters: the topology (Section 9, Part E)

The set `MaxFilter V` of maximal convex filters on `V`, topologized by taking the sets
`Vset C = {F | C ∈ F}`, for `C` closed and convex, as a subbase for the closed sets.

* `separated_iff_disjoint_nhds`: the combinatorial relation `Separated` of
  `ConvexFilters/SpaceCover.lean` is exactly separation by disjoint open sets; this is the
  bridge between Parts A–D and the topology;
* `isCompact_univ`: the space is compact, by Alexander's subbasis theorem;
* `t1Space`: the space is `T₁`;
* `not_t2Space`: on `ℝ × ℝ` it is not Hausdorff.

## Alexander's subbasis theorem

Mathlib was searched for the subbasis criterion for compactness under the names
`alexander`, `subbase`, `subbasis`, and by inspecting the compactness files. The theorem is
present at the pinned revision as `isCompact_generateFrom` in
`Mathlib/Topology/Compactness/Compact.lean` ("Alexander's subbasis theorem"), with a
variant `isCompact_generateFrom'`. It is used here directly, so the fallback route through
Zorn's lemma is not needed; `exists_isMaximal_extension` of `ConvexFilters/Extension.lean`
is still used, to produce the point of the intersection, together with the convex filter
`ofFIP` generated by a family of closed convex sets with the finite intersection property.
-/

namespace ConvexFilter

namespace Space

/-! ### The filter generated by a family with the finite intersection property -/

section FIP

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- A finite intersection of members of a convex filter is a member. -/
theorem biInter_mem (G : ConvexFilter V) (T : Finset (Set V)) (h : ∀ C ∈ T, C ∈ G.carrier) :
    (⋂ C ∈ T, C) ∈ G.carrier := by
  classical
  induction T using Finset.induction_on with
  | empty => simpa using G.univ_mem
  | insert a t ha ih =>
      rw [Finset.set_biInter_insert]
      exact G.inter_mem (h a (Finset.mem_insert_self a t))
        (ih fun C hC => h C (Finset.mem_insert_of_mem hC))

/-- The convex filter generated by a family of closed convex sets all of whose finite
subfamilies have nonempty intersection. -/
def ofFIP (D : Set (Set V))
    (hfip : ∀ T : Finset (Set V), ↑T ⊆ D → (⋂ C ∈ T, C).Nonempty) : ConvexFilter V where
  carrier := {X : Set V | IsClosed X ∧ Convex ℝ X ∧
    ∃ T : Finset (Set V), ↑T ⊆ D ∧ (⋂ C ∈ T, C) ⊆ X}
  isClosed_of_mem := fun _ h => h.1
  convex_of_mem := fun _ h => h.2.1
  univ_mem := ⟨isClosed_univ, convex_univ, ∅, by simp, Set.subset_univ _⟩
  empty_not_mem := by
    rintro ⟨-, -, T, hT, hsub⟩
    obtain ⟨x, hx⟩ := hfip T hT
    exact hsub hx
  inter_mem := by
    classical
    rintro X Y ⟨hXcl, hXcv, T₁, hT₁, hs₁⟩ ⟨hYcl, hYcv, T₂, hT₂, hs₂⟩
    refine ⟨hXcl.inter hYcl, hXcv.inter hYcv, T₁ ∪ T₂, ?_, ?_⟩
    · intro C hC
      rcases Finset.mem_union.mp hC with h | h
      · exact hT₁ h
      · exact hT₂ h
    · have h1 : (⋂ C ∈ T₁ ∪ T₂, C) ⊆ (⋂ C ∈ T₁, C) := by
        intro x hx
        simp only [Set.mem_iInter] at hx ⊢
        intro C hC
        exact hx C (Finset.mem_union_left _ hC)
      have h2 : (⋂ C ∈ T₁ ∪ T₂, C) ⊆ (⋂ C ∈ T₂, C) := by
        intro x hx
        simp only [Set.mem_iInter] at hx ⊢
        intro C hC
        exact hx C (Finset.mem_union_right _ hC)
      exact Set.subset_inter (h1.trans hs₁) (h2.trans hs₂)
  mem_of_superset := by
    rintro X Y ⟨-, -, T, hT, hs⟩ hYcl hYcv hXY
    exact ⟨hYcl, hYcv, T, hT, hs.trans hXY⟩

theorem mem_ofFIP {D : Set (Set V)}
    {hfip : ∀ T : Finset (Set V), ↑T ⊆ D → (⋂ C ∈ T, C).Nonempty}
    {C : Set V} (hC : C ∈ D) (hcl : IsClosed C) (hcv : Convex ℝ C) :
    C ∈ (ofFIP D hfip).carrier := by
  classical
  refine ⟨hcl, hcv, {C}, ?_, ?_⟩
  · simpa using hC
  · simp

end FIP

/-! ### The space of maximal convex filters -/

section Topology

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- The set of maximal convex filters on `V`. -/
def MaxFilter (V : Type*) [NormedAddCommGroup V] [NormedSpace ℝ V] : Type _ :=
  {F : ConvexFilter V // IsMaximal F}

/-- The set of maximal convex filters containing `C`. These sets, for `C` closed and
convex, are the subbasic closed sets. -/
def Vset (C : Set V) : Set (MaxFilter V) := {F : MaxFilter V | C ∈ F.1.carrier}

/-- The subbase of open sets: the complements of the sets `Vset C`, for `C` closed and
convex. -/
def subbase (V : Type*) [NormedAddCommGroup V] [NormedSpace ℝ V] : Set (Set (MaxFilter V)) :=
  {U : Set (MaxFilter V) | ∃ C : Set V, IsClosed C ∧ Convex ℝ C ∧ U = (Vset C)ᶜ}

instance : TopologicalSpace (MaxFilter V) := TopologicalSpace.generateFrom (subbase V)

theorem topology_eq_generateFrom :
    (inferInstance : TopologicalSpace (MaxFilter V)) = TopologicalSpace.generateFrom (subbase V) :=
  rfl

theorem isOpen_compl_Vset {C : Set V} (hcl : IsClosed C) (hcv : Convex ℝ C) :
    IsOpen (Vset C : Set (MaxFilter V))ᶜ :=
  TopologicalSpace.GenerateOpen.basic _ ⟨C, hcl, hcv, rfl⟩

theorem isClosed_Vset {C : Set V} (hcl : IsClosed C) (hcv : Convex ℝ C) :
    IsClosed (Vset C : Set (MaxFilter V)) := by
  rw [← isOpen_compl_iff]
  exact isOpen_compl_Vset hcl hcv

theorem mem_Vset_iff {C : Set V} {F : MaxFilter V} : F ∈ Vset C ↔ C ∈ F.1.carrier := Iff.rfl

theorem MaxFilter.ext {F G : MaxFilter V} (h : F.1.carrier = G.1.carrier) : F = G :=
  Subtype.ext (eq_of_carrier_eq h)

/-! ### The bridge: separation is disjointness of neighbourhoods -/

/-- **The bridge between Parts A–D and the topology.** Two maximal convex filters are
`Separated` exactly when they have disjoint open neighbourhoods in `MaxFilter V`. -/
theorem separated_iff_disjoint_nhds [FiniteDimensional ℝ V] {F F' : MaxFilter V} :
    Separated F.1 F'.1 ↔ ∃ U W : Set (MaxFilter V), IsOpen U ∧ IsOpen W ∧
      F ∈ U ∧ F' ∈ W ∧ Disjoint U W := by
  classical
  constructor
  · rintro ⟨s, hcl, hcv, hcover, hsep⟩
    refine ⟨⋂ E ∈ s.filter (fun E => E ∉ F.1.carrier), (Vset E)ᶜ,
      ⋂ E ∈ s.filter (fun E => E ∈ F.1.carrier), (Vset E)ᶜ, ?_, ?_, ?_, ?_, ?_⟩
    · refine Set.Finite.isOpen_biInter (Finset.finite_toSet _) fun E hE => ?_
      have hEs := (Finset.mem_filter.mp hE).1
      exact isOpen_compl_Vset (hcl E hEs) (hcv E hEs)
    · refine Set.Finite.isOpen_biInter (Finset.finite_toSet _) fun E hE => ?_
      have hEs := (Finset.mem_filter.mp hE).1
      exact isOpen_compl_Vset (hcl E hEs) (hcv E hEs)
    · simp only [Set.mem_iInter, Set.mem_compl_iff, mem_Vset_iff]
      intro E hE
      exact (Finset.mem_filter.mp hE).2
    · simp only [Set.mem_iInter, Set.mem_compl_iff, mem_Vset_iff]
      intro E hE
      obtain ⟨hEs, hEF⟩ := Finset.mem_filter.mp hE
      intro hEF'
      exact hsep E hEs ⟨hEF, hEF'⟩
    · rw [Set.disjoint_left]
      intro G hGU hGW
      obtain ⟨E, hEs, hEG⟩ := exists_mem_of_cover hcl hcv hcover G.2
      simp only [Set.mem_iInter, Set.mem_compl_iff, mem_Vset_iff] at hGU hGW
      by_cases hEF : E ∈ F.1.carrier
      · exact hGW E (Finset.mem_filter.mpr ⟨hEs, hEF⟩) hEG
      · exact hGU E (Finset.mem_filter.mpr ⟨hEs, hEF⟩) hEG
  · rintro ⟨U, W, hU, hW, hFU, hF'W, hdisj⟩
    -- choose, for each subbasic open, a closed convex set defining it
    have hCex : ∀ u : Set (MaxFilter V), ∃ C : Set V,
        u ∈ subbase V → (IsClosed C ∧ Convex ℝ C ∧ u = (Vset C)ᶜ) := by
      intro u
      by_cases h : u ∈ subbase V
      · obtain ⟨C, hC⟩ := h
        exact ⟨C, fun _ => hC⟩
      · exact ⟨∅, fun h' => absurd h' h⟩
    choose Cf hCf using hCex
    have hbasis := TopologicalSpace.isTopologicalBasis_of_subbasis
      (topology_eq_generateFrom (V := V))
    obtain ⟨v, hv, hFv, hvU⟩ := hbasis.exists_subset_of_mem_open hFU hU
    obtain ⟨v', hv', hF'v', hv'W⟩ := hbasis.exists_subset_of_mem_open hF'W hW
    obtain ⟨f, ⟨hffin, hfsub⟩, rfl⟩ := hv
    obtain ⟨g, ⟨hgfin, hgsub⟩, rfl⟩ := hv'
    refine ⟨hffin.toFinset.image Cf ∪ hgfin.toFinset.image Cf, ?_, ?_, ?_, ?_⟩
    · intro E hE
      rcases Finset.mem_union.mp hE with h | h <;>
        obtain ⟨u, hu, rfl⟩ := Finset.mem_image.mp h
      · exact (hCf u (hfsub (hffin.mem_toFinset.mp hu))).1
      · exact (hCf u (hgsub (hgfin.mem_toFinset.mp hu))).1
    · intro E hE
      rcases Finset.mem_union.mp hE with h | h <;>
        obtain ⟨u, hu, rfl⟩ := Finset.mem_image.mp h
      · exact (hCf u (hfsub (hffin.mem_toFinset.mp hu))).2.1
      · exact (hCf u (hgsub (hgfin.mem_toFinset.mp hu))).2.1
    · refine cover_of_forall_mem fun G hG => ?_
      by_contra hcon
      push_neg at hcon
      have hGf : (⟨G, hG⟩ : MaxFilter V) ∈ ⋂₀ f := by
        intro u hu
        have hspec := hCf u (hfsub hu)
        rw [hspec.2.2]
        simp only [Set.mem_compl_iff, mem_Vset_iff]
        refine hcon (Cf u) ?_
        exact Finset.mem_union_left _
          (Finset.mem_image_of_mem Cf (hffin.mem_toFinset.mpr hu))
      have hGg : (⟨G, hG⟩ : MaxFilter V) ∈ ⋂₀ g := by
        intro u hu
        have hspec := hCf u (hgsub hu)
        rw [hspec.2.2]
        simp only [Set.mem_compl_iff, mem_Vset_iff]
        refine hcon (Cf u) ?_
        exact Finset.mem_union_right _
          (Finset.mem_image_of_mem Cf (hgfin.mem_toFinset.mpr hu))
      exact (Set.disjoint_left.mp hdisj (hvU hGf)) (hv'W hGg)
    · intro E hE
      rintro ⟨hEF, hEF'⟩
      rcases Finset.mem_union.mp hE with h | h <;>
        obtain ⟨u, hu, rfl⟩ := Finset.mem_image.mp h
      · have hspec := hCf u (hfsub (hffin.mem_toFinset.mp hu))
        have : F ∈ u := hFv u (hffin.mem_toFinset.mp hu)
        rw [hspec.2.2] at this
        exact this hEF
      · have hspec := hCf u (hgsub (hgfin.mem_toFinset.mp hu))
        have : F' ∈ u := hF'v' u (hgfin.mem_toFinset.mp hu)
        rw [hspec.2.2] at this
        exact this hEF'

/-! ### Compactness -/

/-- **The space of maximal convex filters is compact.** Alexander's subbasis theorem
reduces this to the finite intersection property of the subbasic closed sets, which holds
because a family of closed convex sets whose finite subfamilies lie in a common maximal
filter generates a convex filter, and every convex filter extends to a maximal one. -/
theorem isCompact_univ : IsCompact (Set.univ : Set (MaxFilter V)) := by
  classical
  refine isCompact_generateFrom (topology_eq_generateFrom (V := V)) ?_
  intro P hP hcover
  by_contra hcon
  push_neg at hcon
  -- choose, for each subbasic open, a closed convex set defining it
  have hCex : ∀ u : Set (MaxFilter V), ∃ C : Set V,
      u ∈ subbase V → (IsClosed C ∧ Convex ℝ C ∧ u = (Vset C)ᶜ) := by
    intro u
    by_cases h : u ∈ subbase V
    · obtain ⟨C, hC⟩ := h
      exact ⟨C, fun _ => hC⟩
    · exact ⟨∅, fun h' => absurd h' h⟩
  choose Cf hCf using hCex
  set D : Set (Set V) := Cf '' P with hD
  -- every finite subfamily of `D` lies in a common maximal filter, hence has nonempty
  -- intersection
  have hfip : ∀ T : Finset (Set V), ↑T ⊆ D → (⋂ C ∈ T, C).Nonempty := by
    intro T hT
    have hTsub : ∀ C ∈ T, ∃ u ∈ P, Cf u = C := by
      intro C hC
      obtain ⟨u, hu, huC⟩ := hT hC
      exact ⟨u, hu, huC⟩
    choose! uf huP hufC using hTsub
    set Q : Set (Set (MaxFilter V)) := uf '' ↑T with hQ
    have hQP : Q ⊆ P := by
      rintro u ⟨C, hC, rfl⟩
      exact huP C hC
    have hQfin : Q.Finite := (T.finite_toSet).image uf
    obtain ⟨G, -, hGQ⟩ : ∃ G ∈ (Set.univ : Set (MaxFilter V)), G ∉ ⋃₀ Q :=
      Set.not_subset.mp (hcon Q hQP hQfin)
    have hmemG : ∀ C ∈ T, C ∈ G.1.carrier := by
      intro C hC
      have huQ : uf C ∈ Q := ⟨C, hC, rfl⟩
      have hnot : G ∉ uf C := fun hmem => hGQ ⟨uf C, huQ, hmem⟩
      have hspec := hCf (uf C) (hP (huP C hC))
      rw [hspec.2.2] at hnot
      rw [Set.notMem_compl_iff] at hnot
      rw [← hufC C hC]
      exact hnot
    exact nonempty_of_mem (biInter_mem G.1 T hmemG)
  -- the generated filter, extended to a maximal one, contains every member of `D`
  obtain ⟨G₀, hsub, hmax₀⟩ := exists_isMaximal_extension (ofFIP D hfip)
  obtain ⟨u, huP, hu⟩ := hcover (Set.mem_univ (⟨G₀, hmax₀⟩ : MaxFilter V))
  have hspec := hCf u (hP huP)
  rw [hspec.2.2] at hu
  rw [Set.mem_compl_iff, mem_Vset_iff] at hu
  exact hu (hsub (mem_ofFIP (D := D) (hfip := hfip) ⟨u, huP, rfl⟩ hspec.1 hspec.2.1))

/-! ### The `T₁` property -/

/-- **The space of maximal convex filters is `T₁`.** A maximal filter is the intersection
of the subbasic closed sets containing it. -/
theorem t1Space : T1Space (MaxFilter V) := by
  refine ⟨fun F => ?_⟩
  have hEq : ({F} : Set (MaxFilter V)) = ⋂ C ∈ F.1.carrier, Vset C := by
    ext G
    simp only [Set.mem_singleton_iff, Set.mem_iInter, mem_Vset_iff]
    constructor
    · rintro rfl C hC
      exact hC
    · intro h
      exact (MaxFilter.ext (Set.Subset.antisymm h (F.2 G.1 h))).symm
  rw [hEq]
  refine isClosed_biInter fun C hC => ?_
  exact isClosed_Vset (F.1.isClosed_of_mem hC) (F.1.convex_of_mem hC)

/-! ### Failure of the Hausdorff property -/

open SigCounterexample in
/-- **The space of maximal convex filters on the plane is not Hausdorff.** The line filter
and the filter confined to the line from the right are distinct points that cannot be
separated, by Theorem 9.4. -/
theorem not_t2Space : ¬ T2Space (MaxFilter (ℝ × ℝ)) := by
  intro hT2
  have hne : (⟨Fline, Fline_isMaximal⟩ : MaxFilter (ℝ × ℝ)) ≠ ⟨Ghyp, Ghyp_isMaximal⟩ := by
    intro h
    have hcar : Fline.carrier = Ghyp.carrier := congrArg (fun G => G.1.carrier) h
    have hmem : upRay 0 ∈ Fline.carrier :=
      (mem_Fline_iff (upRay_isClosed 0) (upRay_convex 0)).mpr ⟨0, subset_rfl⟩
    rw [hcar] at hmem
    refine notMem_carrier_of_base_disjoint hyp_mem_Ghyp (n := 0) ?_ hmem
    ext p
    simp only [Set.mem_inter_iff, Set.mem_empty_iff_false, iff_false, not_and]
    intro hp hup
    exact absurd (hup.2 : p.1 = 0) (ne_of_gt (hyp_pos hp))
  obtain ⟨U, W, hU, hW, hFU, hGW, hdisj⟩ := @t2_separation _ _ hT2 _ _ hne
  exact not_separated_Fline_Ghyp
    (separated_iff_disjoint_nhds.mpr ⟨U, W, hU, hW, hFU, hGW, hdisj⟩)

end Topology

end Space

end ConvexFilter
